### ISSUE TITLE
test wrongly flagged as "or later"

### ISSUE THREAD

**Issue by jonassmedegaard** [nexB/scancode-toolkit#1023]
src/licensedcode/data/rules/lgpl_29.yml says that test is lgpl-2.0-plus but the content clearly states it is *only* lgpl-2.0.

**Comment by jonassmedegaard** [comment]
ah, scratch that.

**Comment by pombredanne** [comment]
@jonassmedegaard Actually this is a rare and weird license mention. 

I think it was categorized alright with  an lgpl-2.0-plus since this mention only LGPL and no specific version. Now your raises an interesting point which is that the text `so you can use,modify, distribute and sell under the terms of LGPL *only*.` is kind of vague wrt. to what the mention `LGPL *only*` really means: does it make it incompatible with the GPL for instance? I did not track where this sample came from originally but this is a rather old rule.

Searching it for it on the web is rather weird as most results seem to be for scancode rule.

This other rule is mostly the same too: https://github.com/nexB/scancode-toolkit/blob/48aeaf76ce9f53d02223c41c1b2ad1d1ad73b851/src/licensedcode/data/rules/lgpl_16.RULE and one of the tow could be removed alright.

Which piece of code did you find it in? that would be useful to keep a note for this!

**Comment by jonassmedegaard** [comment]
I didn't find it elsewhere.

I used your tests against Licensecheck, and wrongly read it as "under
the terms of LGPL 2.0 *only*." - and I read it like that several times
before I filed it as an issue, then realizing my error and closing the
issue again.
