### ISSUE TITLE
Codebase walk order

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-toolkit#1060]
In the case where we have a Codebase that is made up of a directory with one archive file and a folder of the extracted contents of the archive file, the top-down walk order on this Codebase appears to be:

0. The directory the downloaded archive is in
1. The downloaded archive itself
2. The extracted files of an archive ($(ARCHIVE_NAME)-extract)
3. The rest of the files

It would be nice to know if we will always walk the Codebase in this order

**Comment by pombredanne** [comment]
Yes this is the case by construction since the walk is always sorted, files first then directories as show here https://github.com/nexB/scancode-toolkit/blob/4d78d13d57a939140f46ef443b9674143a0a48b5/src/scancode/resource.py#L325 and here https://github.com/nexB/scancode-toolkit/blob/4d78d13d57a939140f46ef443b9674143a0a48b5/src/scancode/resource.py#L294

Since the Python sort is stable, you will always get this order alright.
We should add a test for this though

**Comment by pombredanne** [comment]
so we have implicit tests of this order but no explicit. And frankly I would not want this to be a guarantee and cast in stone. So unless you disagree I am closing this for now as wontfix
