### ISSUE TITLE
Missing copyright holder sample for the copyright scan

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1087]
```
/**
Copyright 2011

XYZ Company, ABC and DEF
Some address
*/
```
Copyright scan will only return
```
"Copyright 2011"
```
for the above notice which is not entirely correct as the information for the copyright holder is missing.

**Comment by pombredanne** [comment]
@chinyeungli Thank you for the report

A copyright statement must either be on a single line or multiple contiguous lines.
An empty line cannot be jumped... if it were it would introduce a large number of incorrect detections.

So for instance:
```
    Tru64 audio module for SDL (Simple DirectMedia Layer)
    Copyright (C) 2003

    This library is free software; you can redistribute it and/or ....
```

will be detected as `Copyright (C) 2003` and I am not sure we could infer any copyright holder from the text...

And same for 
```
/**
Copyright 2011

Google, Internet Search and Networking Services
42 Main street, Berverly Hills, CA, USA
*/
```
is not detected more than as `Copyright 2011`

but
```
/**
Copyright 2011
Google, Internet Search and Networking Services
42 Main street, Berverly Hills, CA, USA
*/
```

is detected as `Copyright 2011 Google, Internet Search and Networking Services` because there is no line break after `Copyright 2011`

This is a fairly rare case, right?

**Comment by chinyeungli** [comment]
agree it's a rare case

**Comment by pombredanne** [comment]
@chinyeungli there is really not much I can do here, short of publishing guidelines that explain how to craft a detectable copyright. So I am closing for now. Thanks in anycase for the report. 
Note that other cases of truncated copyright are still valuable to repotas they may not be of the same kind.
