### ISSUE TITLE
New Version notification within Scancode Tool

### ISSUE THREAD

**Issue by kaushikk** [nexB/scancode-toolkit#111]
When the user starts Scancode tool, display a message to user that a new version of scancode is available

Development teams using scancode need to be updated with the latest version of the tool. When starting scancode CLI, it will help if a notification message is printed or an extra parameter to command line like 'scancode --check-updates' may also help

**Comment by pombredanne** [comment]
@kaushikk this makes a lot of sense. If you are familiar with the `pip` Python tool, they use a similar approach. Do you think that is something that you could help with?

**Comment by jdaguil** [comment]
@kaushikk this is a nice enhancement. Currently if you did want to compare versions, the way to do this is to run `scancode --version` and compare it to the latest tagged release at https://github.com/nexB/scancode-toolkit/releases

**Comment by pombredanne** [comment]
In terms of implementation, we could reuse or borrow and adapt the code from pip:
https://github.com/pypa/pip/blob/7cea748d0fb2e8980c2676304607426585550b41/pip/utils/outdated.py

This means also that wee should first make scancode available on Pypi: there is no issue per se there since it builds as a wheel all right. With that, the pip code can check on a remote package version and compare it to the locally installed version and alert that it is out of date easily.

Note that making scancode as a Pypi package would also require that all dependencies are also available on Pypi: this should be the case mostly, but some may not: in which case we will need push a Pypi package for these too.

**Comment by mjherzog** [comment]
What are the other pros & cons of offering ScanCode on Pypi? In general it seems to make sense to do so since ScanCode and our other tools are open source and Python, but does this mean that we will redirect people to get it from Pypi as a primary source for stable releases instead of our GH repo?  Is installation from Pypi easier (or not) than our current installation process?

**Comment by pombredanne** [comment]
@mjherzog there are no cons. Either you use the full distro from GH for regular usage, or you would use the Pypi version as a library when used in Python code.

**Comment by mjherzog** [comment]
I assume that this will also work for AboutCode with the same caveats about dependencies.
Is this something that Li knows how to do easily from his other work on DJA ?

**Comment by jdaguil** [comment]
@pombredanne @mjherzog 
I see two possible solutions to check if you have the latest release:
<ol>
<li> Github Releases API. This would allow you to compare versions by pulling the latest version from the API. It's not much work to implement, and it would address the issue reasonably soon.
<li>  Put project on Pypi and use pip. This sounds great; although it might take more research and time to implement.
</ol>

**Comment by pombredanne** [comment]
@jdaguil the pip/pypi way is likely the fastest and simplest and most robust IMHO. We have code that is tested to do that a millions of time per day there.

**Comment by pombredanne** [comment]
and we need to release on Pypi anyway

**Comment by pombredanne** [comment]
See also #24

**Comment by pombredanne** [comment]
This is merged in develop now.
