### ISSUE TITLE
Detect SPDX-License-Identifiers

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#1114]
ScanCode should detect an SPDX-License-Identifier in a file.
There seem to be two approaches:
1. Changes in matching code to detect this string and report the license expression following.
2. Add Rules. This could be a quick fix for the limited current list of Identifiers, but longer-term will likely be problematic with the increasing use of license expressions.

**Comment by pombredanne** [comment]
Actually this has not been documented nor propped much and this is only in the develop branch but the feature is there since ~ mid may: https://github.com/nexB/scancode-toolkit/blob/5e3bd77f82812dcd1cf4a987aa920321e29f5b4a/src/licensedcode/match_spdx_lid.py#L46

**Comment by pombredanne** [comment]
Actually thinking about this more... this is only in free text. We also need this crucially in package manifest so wee get a normalized expression and I think that's what you referred to.

Now, the approach that has been taken for the detection side is the 1. approach you suggested.

1. The matching code has been changed to detect an identifier line and report the license expression that's following. The expressions is parsed and normalized
2. A new synthetic rule is generated on the fly for this matched expression (this later part is needed since we always report a license match for a rule)

**Comment by pombredanne** [comment]
Actually this ticket is about SPDX license id: these are now fully supported.
Detecting further these when used implicitly to describe the license of a package in a manifest is tracked in #1092
