### ISSUE TITLE
MadWifi license?

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#1124]
```
/*-
 * Copyright (c) 2001 Atsushi Onoe
 * Copyright (c) 2002-2005 Sam Leffler, Errno Consulting
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * Alternatively, this software may be distributed under the terms of the
 * GNU General Public License ("GPL") version 2 as published by the Free
 * Software Foundation.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * $Id$
 */
```
The above text is getting from: https://github.com/puzzlet/madwifi/blob/master/net80211/_ieee80211.h
Should the above be detected as `madwifi-dual` instead of `dual-bsd-gpl`
```
"licenses": [
        {
          "key": "dual-bsd-gpl",
          "score": 100.0,
          "short_name": "Dual BSD-GPL",
          "category": "Permissive",
          "owner": "Motorola",
          "homepage_url": "",
          "text_url": "",
          "reference_url": "https://enterprise.dejacode.com/urn/urn:dje:license:dual-bsd-gpl",
          "spdx_license_key": "",
          "spdx_url": "",
          "start_line": 6,
          "end_line": 30,
          "matched_rule": {
            "identifier": "dual-bsd-gpl.LICENSE",
            "license_expression": "dual-bsd-gpl",
            "licenses": [
              "dual-bsd-gpl"
            ]
          }
        }
      ],
```

**Comment by muzsielod** [comment]
Hello,

I think the detection is accurate, because there are a plenty other components with this exact dual license text. Further more the mad-wifi name it's not even part of the license text, this way when detected with the mad-wifi name in an other component will generate confusion. If it's helps you, you can modify it locally for yourself in the license/rule section. 

Anyhow, this is just my opinion.

Thank you.

**Comment by pombredanne** [comment]
Thanks for the report and comments: ambiguities around these licenses seem to be a recurring issue: see the ticket #684.

Here `dual-bsd-gpl` is what is detected here alright and not the `madwifi-dual` and I think this is correct with  the current rule set.


Even though both `dual-bsd-gpl` and `madwifi-dual` licenses are combos of a BSD-like terms with a GPL option, `madwifi-dual` has some extra "without modication" clause and the text are different enough. In fact:

 - `madwifi-dual` is a `intel-bsd` with a GPL choice i.e. the license expression is `intel-bsd OR gpl-2.0`
 - `dual-bsd-gpl` is a `bsd-new` with a GPL choice i.e. the license expression is `bsd-new OR gpl-2.0`

See [madwifi-dual](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/madwifi-dual.LICENSE) and [dual-bsd-gpl](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/dual-bsd-gpl.LICENSE)



##### Now there are some issues still we could resolve in any of these ways:

 1. do nothing: we keep these `dual-bsd-gpl` and `madwifi-dual` licenses as they are (and add extra rules as needed to either one when we find more variants)

 2. use expressions: we could deprecate the `dual-bsd-gpl` and `madwifi-dual` licenses and instead use rules to return license expressions as suggested above for these

 3. use special license keys we have today AND expressions: we could have a way to also include an "expanded" license expression to certain licenses data such as these two... (e.g. the YML for these license 
could have a `license_expression` field with a value possibly of `bsd-new OR gpl-2.0-plus` but this feel like a big modification for just a few rare-enough oddities. This was explored in #522 and finally abandoned. I am not sure we want to re-explore this at all as it has a level of complexity I would like to avoid.

Option 1. or 2 seem the simplest for now, but I am open to any other way.

In reviewing these licenses I also found oddities and/or bugs:

##### A. Some other license variants have some similar terms "without modification" on the notice text or placement:

 - [bsd-innosys.LICENSE](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/bsd-innosys.LICENSE)

 - [bsd-simplified-darwin.LICENSE](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/bsd-simplified-darwin.LICENSE)

 - [bsd-top.LICENSE](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/bsd-top.LICENSE)

 - [intel-bsd.LICENSE](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/intel-bsd.LICENSE) : it has the "without modification" condition together with conflicting terms saying that the disclaimer only has to be similar and seems another source of confusion

 - [madwifi-dual.LICENSE](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/madwifi-dual.LICENSE) : it has the "without modification" condition together with conflicting terms saying that the disclaimer only has to be similar and seems another source of confusion. In fact the `madwifi-dual` is exactly the same text as the `intel-bsd` with the extra choice of GPL added.



##### B. These rules have a "without modification" and wrongly return a bsd-new

 - This rule https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/rules/dual-bsd-gpl.yml and https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/rules/dual-bsd-gpl.RULE point to something entirely different because it of an `without modification` extra condition that applies to the source code notices... See [here](https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/rules/dual-bsd-gpl.RULE#L6) . And http://www.silex.jp/products/license/gdm-3250/License/u-boot/Licenses/bsd-3-clause.txt is detected as plain bsd-new  by this rule in error

 - bsd-new_or_gpl-2.0_8.RULE : this may be a dual-bsd-gpl but "without modification"
 - bsd-new_or_gpl-2.0-plus_2.RULE
 - bsd-new_or_gpl-2.0-plus_4.RULE


##### C. The following rules are potentially buggy and need to be reviewed and requalified (because of the "without modifications" that is not part of the license text they point to):

 - bsd-axis_or_gpl.RULE
 - bsd-axis_or_gpl2.RULE
 - bsd-axis_or_gpl3.RULE
 - bsd-axis_or_gpl4.RULE
 - bsd-axis_or_gpl-2.0-plus.RULE

The bsd-axis is a bsd-new aka. bsd-3-clause but using only clause 1 and 3 (and not clause 2) so this is neither a bsd-simplified nor a bsd-new
So the resolution is likely to create another variant of the bsd-axis with the extra "without modification"

Note also that these license rules are present in the Linux kernel.

##### D. And this test need to be reviewed:
 - bsd-new_and_gpl_and_gpl-2.0_and_intel-bsd-special_and_other.txt



### So in recap here is what I suggest:

1. keep the `dual-bsd-gpl` and `madwifi-dual` licenses as-is for now.
2. introduce a new bsd-new and bsdd-axis variant LICENSES with the extra "without-modification" term
3. fix the rules and tests listed above to point to these new variant  

The alternative to 1. for consideration would deprecate `dual-bsd-gpl` and `madwifi-dual` and replace them by rules:
 - `dual-bsd-gpl` becomes `bsd-new OR gpl-2.0`
 - `madwifi-dual` becomes `intel-bsd OR OR gpl-2.0`


@chinyeungli @muzsielod @DennisClark feedback welcomed. This is messy alright, but we do not have to resolve the mess... just to detect the proper licenses correctly!

**Comment by chinyeungli** [comment]
I tend to vote for `license_expression` option, but I'm fine with either solution.

**Comment by pombredanne** [comment]
ok, so I am going with this:
1. deprecate  `dual-bsd-gpl` and replace it with `bsd-new OR gpl-2.0` in rules and tests
2. deprecate `madwifi-dual` and replace it with `intel-bsd OR gpl-2.0` in rules and tests
3.  we have a new `bsd-new-nomod`  and http://www.silex.jp/products/license/gdm-3250/License/u-boot/Licenses/bsd-3-clause.txt  is detected this way OK now
4. f8f70ccbdff3b8a33253ff3b7f91ec99fc22a066 has added a `no mod` variant for bsd-axis.

So all the points of https://github.com/nexB/scancode-toolkit/issues/1124#issuecomment-402159629 are pushed now.

**Comment by pombredanne** [comment]
This is in a branch for now and will be pushed to develop soon

**Comment by pombredanne** [comment]
This has been fixed in develop
