### ISSUE TITLE
Include full license texts / offline html page

### ISSUE THREAD

**Issue by ened** [nexB/scancode-toolkit#123]
During our talks with the lawyer, they requested a full _offline_ version of the HTML output in order to comply with the various legal constraints that LGPL/Apache/GPL etc bring.

That means:
* No external links for licenses
* Full copies of all license texts included in the HTML page (at the bottom)

Does the project already include the full copies of the license text somewhere? I'd like to contribute this feature.

**Comment by pombredanne** [comment]
@ened What is the purpose? 
Is this to generate an attribution document to accompany redistributed software?
Or is this to collect all actual detected license texts, notices and mentions?

>Does the project already include the full copies of the license text somewhere?
All the texts are in https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data

**Comment by ened** [comment]
Because we are going to ship a version of the html-document with an embedded device, which MAY NOT have an active internet connection at the time of an legal check.

However, most license require full attribution and a full copy within the attribution document.

Thanks for the link to the texts. My proposal is this to add one option to ./scancode, like "--license-full-attribution", which will trigger this within the html template.

**Comment by ened** [comment]
> Is this to generate an attribution document to accompany redistributed software?

Yes. For a Android system.

**Comment by pombredanne** [comment]
ok, this makes sense. In earnest I never thought of this output as a possible attribution doc....
For this there is another tool called `AboutCode` https://github.com/dejacode/about-code-tool 
But it is not yet integrated in ScanCode...
That said, to collect all the texts there are a few aspects to consider:
1. The actual texts matched may need to be extracted: they may differ slightly from the reference texts  which is the whole purpose of the license detection. Since the returned license detection results contain internally the line and character offsets of the matched to regions, this can be automated.
2. These should be returned in the scan results and a custom template could then make use of them (or they could be processed in another way from the JSON data)

There are a few caveats to be aware though: 
1. the scans should always be reviewed IMHO first.
2. some of the detected licenses may be incomplete for correct attribution production. For instance say only an LGPL-3.0 notice is present and was detected. Since the LGPL-3.0 is an exception to the GPL-3.0, a correct and accurate attribution should contain eventually the notice, with eventual copyrights, and the full texts of both the LGPL-3.0 and GPL-3.0. This cannot be inferred entirely from the actual scan results nor the actual metadata available with each license..
There are likely a few more issues to pop up.

**Comment by pombredanne** [comment]
@ened directly related is also the techniques used in Android for producing license attribution.
I wrote an article on the topic that may be of interest too:
http://www.aboutcode.org/android_case_study.html

**Comment by ened** [comment]
Indeed, super interesting. Thank you for point me to that article.
The current task is to get the kernel copyright holders first, then later I need to work on the Android NOTICE.html file as well. This seems to be some copy-paste only.

Regarding the full license text, I needed to add one change to they `get_licenses` function in `api.py`. 

Basically, we just need to add this line:
```
result['text'] = lic.text
```

Then the full license text becomes available in the template.

Is there a unit test which needs to be changed as well or is a simple PR sufficient?

**Comment by pombredanne** [comment]
> The current task is to get the kernel copyright holders

Just to make sure, you have not been asked to collect the whole set of the Linux Kernel copyrights ?
I am asking, because I have never seen a lawyer ask for that.

**Comment by ened** [comment]
Yes, the JSON test now fails because it will take all fields, so we will:
 - need either an option or exclude it manually
 - switch the JSON formatter to use a template instead of all fields

> Just to make sure, you have not been asked to collect the whole set of the Linux Kernel copyrights ?
> I am asking, because I have never seen a lawyer ask for that.

Yes I've been asked to provide that and they insist it is needed.

**Comment by pombredanne** [comment]
About adding a get_license in the API, the problem in doing do that here is that the license text will always be included in all outputs, which would make things a tad heavy.

I think that instead of doing this, you could you pass a License object to the template data dictionary here:
https://github.com/nexB/scancode-toolkit/blob/124_custom_template/src/scancode/format.py#L171
something more or less like:
```
from licensedcode.models import get_license
...
if entry['key'] not in licenses:
    licenses[entry['key']] = entry
    entry['object'] = get_license(entry['key'])
```
Then the license text will be available there but will be lazily loaded only there if requested in the template for instance with this:
```
        {% for key, license in licenses.items() %}
            <p>{{ license.object.text }}</p>
        {% endfor %}
```

**Comment by pombredanne** [comment]
>Yes I've been asked to provide that and they insist it is needed.

Your call. This is a noble goal, but afaik, nobody ever did that before: none of the Linux distributors does this, and none of the Android device manufacture do this either, to the best of my knowledge.

**Comment by pombredanne** [comment]
and for the PR you probably best off building on top or branching from the branch of #124

**Comment by pombredanne** [comment]
All set and merged... Thanks!
