### ISSUE TITLE
Optional line numbers

### ISSUE THREAD

**Issue by ened** [nexB/scancode-toolkit#124]
The simple html report should have an option to remove the line numbers from the output.

**Comment by pombredanne** [comment]
The HTML output is defined by a Jinja template:
https://github.com/nexB/scancode-toolkit/blob/develop/src/scancode/templates/html/template.html

For now, the template path used is hardcoded. 
How would envision this? 
I could imagine an option to pass a custom template instead of the default one. In this case you could create a custom report (in HTML or any other text format) by creating a custom Jinja template...
Would this be something like that that you envision?

**Comment by ened** [comment]
How about a cmd line option to control the columns in the html-template?

```
./scancode --license-columns=key,short_name,category,owner,dejacode_url,homepage_url,text_url, \
    spdx_license_key,spdx_url
./scancode --license-columns=all # the default
./scancode --license-columns=short_name,text_url
```

Within the template, we could use something like `{% if column.included('key') %}<th>key</th>{% endif %}`

**Comment by ened** [comment]
Note, my example is made for the license table, but should be adjusted appropriately for the copyright table.

**Comment by pombredanne** [comment]
@ened the thing with your proposed approach is that it binds command line options with expected instructions in the template. Also you then need to have a set of new cli option and that for each scan type (there are a few more coming) up.  Combining the two is likely to produce a rather bloated CLI and code IMHO.

I would be more in favor of a custom template, especially since the data content will evolve (and is evolving quickly).

**Comment by ened** [comment]
Ok, that would then be something like this?

```
./scancode --template=/path/to/template.html
```

If you agree, I will work on this function.

**Comment by pombredanne** [comment]
@ened you can try this branch: https://github.com/nexB/scancode-toolkit/tree/124_custom_template
There the `--format` option can now accept either a standard format such as html, html-app or json or a path to a custom Jinja template.
You can copy the standard template as a base: https://github.com/nexB/scancode-toolkit/tree/c1e70994abe8ceb18bc99aa6f81ebc40d832fb7f/src/scancode/templates/html
Then use `--format <path to your custom template>` to render the output with this template

If this works for you, then you can update and refine and submit a PR; adding a few tests would be great!

**Comment by pombredanne** [comment]
I think we are all set and all is merged in the develop branch!
Thanks ++ for this, my Lord!
