### ISSUE TITLE
Add Greensock "No Charge" license

### ISSUE THREAD

**Issue by jonasob** [nexB/scancode-toolkit#1302]
The Greensock "No Charge" license is not an Open Source license, but code covered by it is distributed through npm and as such, gaining some use despite the restrictiveness of the license. It would be useful for ScanCode to be able to detect the license.

Here's an example copyright header: https://github.com/greensock/GreenSock-JS/blob/master/src/uncompressed/TimelineMax.js

Possibly matching on simply the URL referenced: https://greensock.com/standard-license would be sufficient.  An earlier URL for the same license is http://www.greensock.com/terms_of_use.html and is also sometimes used.

**Comment by pombredanne** [comment]
Thank you! That's an easy one.

For non-open source, non-free licenses there are two options:
1. create a new license (and rules if needed)
2. create only rules under the `proprietary` or `commercial-license` license keys

Either way works. If you have a commercial license with them, then it can be useful to report this as it own license. Otherwise new rules under `proprietary` are enough in most cases and avoid license key inflation.

**Comment by pombredanne** [comment]
@jonasob for now, I pushed a few rules for the `proprietary` license. We can update this to a bona fide license of its own if needed.
See #1304

**Comment by jonasob** [comment]
This looks good to me!

**Comment by pombredanne** [comment]
This is merged and fixed in develop
