### ISSUE TITLE
autoconf-exception-2.0.LICENSE contents differ from SPDX one

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#1319]
I just realized that the contents of [autoconf-exception-2.0.LICENSE](https://raw.githubusercontent.com/nexB/scancode-toolkit/develop/src/licensedcode/data/licenses/autoconf-exception-2.0.LICENSE) differ quite clearly from SPDX' [Autoconf-exception-2.0.txt](https://github.com/spdx/license-list-data/raw/master/text/Autoconf-exception-2.0.txt). Who's right?

**Comment by pombredanne** [comment]
@sschuberth how shocking! good catch...

The SPDX version is what should be used there for sure since there is an SPDX id.
FWIW, Autoconf exceptions are a tad messy and come in many variations.

I do not know where the SPDX text comes from as this is a rather rare one vs. the one we have right now: - 392 hits https://www.google.com/search?q=%22This%20special%20exception%20to%20the%20GPL%20applies%20to%20versions%20of%20Autoconf%20released%20by%20the%20Free%20Software%20Foundation.%22
- vs the current text with 45500 hits https://www.google.com/search?q=%22as%20part%20of%20a%20program%20that%20contains%20a%20configuration%20script%20generated%20by%20Autoconf%22 

And we track two other variants of Autoconf exceptions:
- `autoconf-macro-exception`
- `autoconf-simple-exception` which is the same as this text but with an explicit GPL 3.0 reference

In terms of resolution, here is what I could think of:
1. `autoconf-simple-exception` stays as it is for now or is renamed to `autoconf-simple-exception-3.0` since it is 3.0 specific
2. we create a `autoconf-simple-exception-2.0` to track the text that `autoconf-exception-2.0` has right now
3. we update `autoconf-exception-2.0` to have the SPDX text

In addition this would be worth bringing to the attention of the SPDX legal team: the exception that is tracked seems to be for the autoconf core code proper, vs. the one that is tracked here is the one that is used in autoconf/autotools generated code: the later is much more common than the former

**Comment by sschuberth** [comment]
To clarify: I guess we'd have to do *all* of 1., 2., and 3., not just either one, right? At least if we do 2., we should also do 3., IMO. I'm happy with any resolution that makes the same file name (not taking into account letter-case-differences) in ScanCode and SPDX contain the same text (not taking into account trivial formatting changes).

**Comment by pombredanne** [comment]
yes we need all of 1.2.3. And yes ScanCode is aligned with SPDX texts for SPDX-listed licenses

**Comment by pombredanne** [comment]
Closing as this has been merged in develop
