### ISSUE TITLE
PPM without license wrongly recognized as CC-BY-4.0, plus author false positives

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#1347]
https://github.com/dtschump/CImg/blob/master/examples/img/parrot.ppm

is recognized as CC-BY-4.0 and there are also wrong author statements.

**Comment by pombredanne** [comment]
Thanks. I think I will exclude all "media" from copyright and license detection.

**Comment by armijnhemel** [comment]
Of course media can contain these texts, but those should be extracted in a different way :-)

**Comment by pombredanne** [comment]
@armijnhemel the current way is that licenses and copyrights are detected on files that can "contain text". The check is done here: https://github.com/nexB/scancode-toolkit/blob/617d59a45fce0125bd54e6438f929dcc382d26e0/src/typecode/contenttype.py#L520 and there https://github.com/nexB/scancode-toolkit/blob/617d59a45fce0125bd54e6438f929dcc382d26e0/src/textcode/analysis.py#L178

For now I will return False for media files... and we can later deal with this using proper parsers.
Otherwise there are too many false positives with media files.

**Comment by pombredanne** [comment]
this is fixed, merged and released:
```
  "files": [
    {
      "path": "parrot.ppm",
      "type": "file",
      "licenses": [],
      "license_expressions": [],
      "holders": [],
      "copyrights": [],
      "authors": [],
      "scan_errors": []
    }
```
@armijnhemel thanks ++ for the report!
