### ISSUE TITLE
Add Conda meta.yml manifest parser

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1447]
### Description
See for example https://github.com/bioconda/bioconda-recipes/blob/master/recipes/abeona/meta.yaml#L42

This is the format used by  Conda and bioconda

**Comment by shubhscoder** [comment]
@pombredanne I am interested in taking this ! Can you guide me on this ? Thank you so much!

**Comment by shubhscoder** [comment]
@pombredanne is  (scancode-toolkit/src/packagedcode/jar_manifest.py) the right file to look?

**Comment by PyAgni** [comment]
@pombredanne I'm willing to do this if anyone already hasn't been assigned. I have a few questions:

- We have to use PyYaml for this. Right? Or this has to be done by any other method?
- Once parsed, the collected metadata from the manifest has to be stored in a variable(say 'package'). And make an object that returns that package.
- Do we also need to make unittests for the parser?

And since I'm already working on #295 I'll try to make this python 2/3 compatible.

**Comment by shubhscoder** [comment]
Hi Agni, I am trying to complete this as my first issue. Would you mind
helping me in this ?

**Comment by PyAgni** [comment]
Hello @shubhscoder . Although I'm new here, I would love to help you. I don't have prior experience with yml files but the format seems pretty straight forward if you have worked JSON files or something similar. I think we have to write a script to parse all the contents of the meta.yml file like package details,requirements,about etc. Then we would also probably need to create unittests for that script. (See tests folder) 
Apart from this @pombredanne  will be able to clarify more about it.

**Comment by shubhscoder** [comment]
Hello @PyAgni we can work together on this. Thank you!

**Comment by pombredanne** [comment]
@PyAgni @shubhscoder you can see the many parsers available in `src/packagedcode`. The main purpose is to normalize the data in our Package model objects. A recent and simple one was contributed by @ritiek in #1426 for Rust Cargo for instance. 

About  YAML: we do not use PyYAML directly.  We use instead the `saneyaml` parser. Search for "saneyaml" for details.
And we always write automated tests of course.

**Comment by pombredanne** [comment]
I would be good to start looking into this. @linexb do you mind taking a look?

**Comment by epruesse** [comment]
FYI: While the files in the recipes are called `meta.yaml`, they are not actually valid yaml. Example:

```
{% set name = "package-name" %}
package:
  name: {{ name }}
  version: 0.10
source:
  url: https://somewhere   # [py2k and osx]
  url: https://elsewhere  # [py3k or linux]
requirements:
  build:
    - {{ compiler('cxx') }}
```

The above demonstrates three divergences.

1. The file is passed through Jinja2 for evaluation. Several functions are available to handle e.g. compiler selection or common values or dynamic dependencies.
2. The file may have line based selectors of the form `# [expression]` where the expression is evaluated as python code. Lines with selectors in which the expression evaluates to false are omitted. This can lead to duplicate key errors in YAML.
3. Parsing of float numbers is disabled. In the above example, unmodified YAML parsing would lead to a version `0.1`, not `0.10`. 

Options for sidestepping this:
- use conda-build.api.render to "render" the recipe into a set of MetaData objects. Have a look at bioconda-utils for options you should set so this does not take forever.
- use bioconda_utils.recipe.Recipe to parse the recipe.
- roll your own
- parse the packages instead of the recipes. Each package contains a `info` folder in which several json files can be found. They are not 100% complete, not everything is copied, but perhaps they suffice for your purposes.

**Comment by pombredanne** [comment]
@epruesse thank you ++ for chiming in and for the precious guidance: that's extremely gentle of you!

**Comment by linexb** [comment]
In one of our test case, the test file is: https://repo.continuum.io/pkgs/free/linux-ppc64le/requests-kerberos-0.8.0-py35_0.tar.bz2

By extracting the file and extracting the inside tar recipe.tar, we get the meta.yaml and parse it.

In the mean while, there are a few other files along with recipe.tar which contain useful package information, for example, info/about.json and info/license.txt

**Comment by pombredanne** [comment]
This is now merged in develop
