### ISSUE TITLE
Restrictive licenses detected as mozilla-gc

### ISSUE THREAD

**Issue by rdoeffinger** [nexB/scancode-toolkit#1560]
### Description
A file with the following contents is detected as mozilla-gc:

/*
PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
THIS SOFTWARE FOR INTERNAL USE ONLY
*/

(this is only part of the full, proprietary, license text)
I don't know how the code works, but I would suggest a license should never be detected as mozilla-gc unless the words "for any purpose" actually appear in it.

### System configuration
Tested on Linux, head of develop: 40e7192f71f3a9b9822aeba44441d08b67736a7a
Ran command:
./scancode -l --html test.html test.LICENSE

**Comment by pombredanne** [comment]
@rdoeffinger Thank you for this report. You said:
> PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
THIS SOFTWARE FOR INTERNAL USE ONLY
> (this is only part of the full, proprietary, license text)

I thought for a second that this license was part of Linux code. But reading again it was clear this is not and you used ScanCode on Linux instead.

Could you attach or paste this agreement of yours so it could be included as a detectable text? The fragment you posted is rather unique and never seen anywhere else, so I will add that as a `proprietary-license` sample text (we call these RULEs https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules )

> I don't know how the code works, but I would suggest a license should never be detected as `mozilla-gc` unless the words "for any purpose" actually appear in it.


We use multiple techniques for detection, but they are driven by content not by specific inclusion or exclusion patterns so I could not just say to detect `mozilla-gc` only if certain words are present. Eventually the key ingredients are automatons and a full pairwise diff and a large data set of license and notice texts.  After matching, there is also a final merge and cleanup step where some text-specific computed thresholds are taken into account and these can also be set manually. What I could do here is to require some minimum coverage of the `mozilla-gc` text to be present to trigger this detection. 

But rather than doing an exception that is likely highly specific to you agreement text, it would be much better and more efficient to have the full text of your proprietary agreement in ScanCode as a `proprietary-license` example. Any bits of the `mozilla-gc` texts it contains would be subsumed as contained in it when your text will be scanned and matched.

**Comment by rdoeffinger** [comment]
Sorry for the unclear wording! Didn't think about it since I was just following the bug reporting instructions, oops.
The problem I see with this approach of including the full license is that there are so incredibly many proprietary licenses that it seems a bit worrying to me if they are likely to be identified as permissive licenses instead by default - probably just due to the fact that most licenses in scancode are permissive licenses!
There is also the problem that if you are pedantic (at least for longer licenses) you can't really include the license unless you actually have a license for the license text itself I guess.
Anyway as it's fairly minimal, here is the text (except for company name, which might change anyway):

THIS SOFTWARE CONTAINS CONFIDENTIAL INFORMATION AND TRADE SECRETS OF ...
.... PERMISSION IS HEREBY GRANTED TO USE, MODIFY, AND/OR COPY
THIS SOFTWARE FOR INTERNAL USE ONLY PROVIDED THAT THE ABOVE COPYRIGHT NOTICE 
APPEARS IN ALL COPIES OF THIS SOFTWARE.

And here is the csv extract of the match result:

Resource,type,is_legal,is_manifest,is_readme,is_top_level,is_key_file,scan_errors,license_expression,license__key,license__score,license__name,license__short_name,license__category,license__is_exception,license__owner,license__homepage_url,license__text_url,license__reference_url,license__spdx_license_key,license__spdx_url,start_line,end_line,matched_rule__identifier,matched_rule__license_expression,matched_rule__licenses,matched_rule__is_license_text,matched_rule__is_license_notice,matched_rule__is_license_reference,matched_rule__is_license_tag,matched_rule__matcher,matched_rule__rule_length,matched_rule__matched_length,matched_rule__match_coverage,matched_rule__rule_relevance,copyright,copyright_holder,author
NN,,,,,,,,,mozilla-gc,8.11,Mozilla GC License,Mozilla GC License,Permissive,False,Mozilla,,http://www.hboehm.info/gc/license.txt,https://enterprise.dejacode.com/urn/urn:dje:license:mozilla-gc,,,7,7,mozilla-gc.LICENSE,mozilla-gc,[u'mozilla-gc'],True,False,False,False,3-seq,74,6,8.11,100.00,,,

**Comment by pombredanne** [comment]
@rdoeffinger Thank you . I added the larger license text as detection rule and will push the updated branch soon.

> The problem I see with this approach of including the full license is that there are so incredibly many proprietary licenses that it seems a bit worrying to me if they are likely to be identified as permissive licenses instead by default - probably just due to the fact that most licenses in scancode are permissive licenses!

That's were the scoring returned with the matches helps. Since we do a diff in the end there is little risk to mis identify a proprietary license for a permissive one unless:
1. the  proprietary license contains the text of the permissive one
2. AND it contains no other thing that could be otherwise be part of licenses we already have


So the approach is to collect enough variety so we have some examples of the most common wordings of proprietary licenses.

> There is also the problem that if you are pedantic (at least for longer licenses) you can't really include the license unless you actually have a license for the license text itself I guess.

That's a good one! indeed. Though proprietary licenses are rarely explicitly licensed, they are often confidential. We will take what we can and is public and we can sanitize the input from names too!

**Comment by pombredanne** [comment]
Thank you!
This is now fixed in PR #1552
It will be merged as soon as the tests all pass.
