### ISSUE TITLE
Incorrect Copyright holder detection

### ISSUE THREAD

**Issue by nrbrook** [nexB/scancode-toolkit#1602]
### Description
Given the copyright notice:
```
//  Copyright © 2018 Some Company Ltd. All rights reserved.
```
The copyright detected is `Copyright (c) 2018`
I would expect the value to be `Some Company Ltd`. This also means this file is not ignored when using `--ignore-copyright-holder="Some Company Ltd"`

### System configuration
macOS 10.14.5 (18F132)
Scancode https://github.com/nexB/scancode-toolkit/commit/1858047f7249cda2860cc573d29fb35c99c16b60
Source download

**Comment by pombredanne** [comment]
@nrbrook thank you for the report. I cannot use `//  Copyright © 2018 Some Company Ltd. All rights reserved.`  I would need some real name as the copyright detection is using a part of speech tagger and the tagging part is aware of the meaning of many words so "Some Company" many not work at all. I would need at least something using made up names that uses the exact same case and punctuation and number of words as in the original.

And I am asking all this because I am sure you have a bug BUT the "sanitized" example you provided works nicely otherwise with the latest develop:
```
$ cat some
//  Copyright © 2018 Some Company Ltd. All rights reserved.

$ scancode --json-pp - -c some 
Setup plugins...
Collect file inventory...
Scan files for: copyrights with 1 process(es)...
[####################] 1              
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "3.0.2.post826.a68e95b.dirty.20190614144620",
      "options": {
        "input": [
          "some"
        ],
        "--copyright": true,
        "--json-pp": "-"
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2019-06-14T144625.930354",
      "end_timestamp": "2019-06-14T144626.240200",
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "some",
      "type": "file",
      "holders": [
        {
          "value": "Some Company Ltd.",
          "start_line": 1,
          "end_line": 1
        }
      ],
      "copyrights": [
        {
          "value": "Copyright (c) 2018 Some Company Ltd.",
          "start_line": 1,
          "end_line": 1
        }
      ],
      "authors": [],
      "scan_errors": []
    }
  ]
}
```

Alternatively you can send me the text privately at pombredanne@nexb.com and I will not make it public.

**Comment by nrbrook** [comment]
You are correct, the copyright notice used only had the company name (1 word), not Ltd, and was not detected as part of the copyright notice. I'm not sure if that should be considered a bug. I just changed the copyright notice.
