### ISSUE TITLE
Terminal crashes when tab-completion paths 

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#1647]
### Description
On a fresh scancode develop checkout, the terminal crashes when trying to tab complete paths (when specifying the root location of your scan). 

Steps to reproduce:
1) git clone a new scancode-toolkit checkout
2) run `source configure`
3) type `scancode -i s` and hit tab (attempt to tab complete samples dir)
4) it will crash the terminal

I can reproduce this every time. 

Possibly related to: #1638 

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? **Ubuntu 1804**
* What version of scancode-toolkit was used to generate the scan file?: **Latest develop**
* What installation method was used to install/run scancode?: **Source Download**

**Comment by pombredanne** [comment]
@majurg thank you: a nasty one indeed. I traced this to this: https://github.com/nexB/scancode-toolkit/commit/abe7aafdf85c9fcf006f99725aa7e51d83acbdd6

So since I still want configure to fail loudly on any error, the fix is to restore shell default error handling at the end with a `set +e` at the end.... I am not sue this is best though as when you source configure and this  fails, your shell will be left with set -e... What's needed is a try/finally :)

**Comment by pombredanne** [comment]
This is ready for testing in develop now.

**Comment by majurg** [comment]
@pombredanne The latest develop no long has this issue, thanks!
