### ISSUE TITLE
Where to find the Rules used for License detection

### ISSUE THREAD

**Issue by ChinnuJose** [nexB/scancode-toolkit#1738]
Hi,

Can you please tell me where we can find the Rules which is used to find the licenses.  
I could only see the import, but not sure where to check the exact rules used. 

I am using Linux Redhat 7.3 & ScanCode 3.0.2

Also, in script its mentioned to ignore these license, but scan code still find zlib. SO how can we deactivate any rules?

# these key would create too many false positives if added. We ignore these
very_common_ids = set( 'xskat',
    'zed',
    'zend-2.0',
    'zlib',
])

**Comment by ChinnuJose** [comment]
I was able to locate the Rules & License folder.
So could you please help me to deactivate custom rules.

**Comment by pombredanne** [comment]
@ChinnuJose  you wrote:

> we ignore these very_common_ids = set( 'xskat',
'zed',
'zend-2.0',
'zlib',
])

if there is ANY license that is not detected correctly, you should report a ticket here and this will be fixed. Disabling a few rules locally is possible (just delete them) but this is not a solution in 99.999% of the cases and is not a fix that is then shared with everyone.  So please report a ticket for each incorrect license detection.

There are also several (like over 1000's ++) of new and improved license detection rules that have been added or updated since version 3.0.2. (the latest release candidate for 3.1 is 3.1.1) so IMHO you should also try 3.1.1

**Comment by ChinnuJose** [comment]
We will try with the new version once.
Also, can you please let me know from where the Key is identified, as far my understanding, its the word from the package file, and hope it does not depend on the scan code.

**Comment by pombredanne** [comment]
@ChinnuJose re:

> Also, can you please let me know from where the Key is identified, as far my understanding, 

Do you mean where the license key is defined?
