### ISSUE TITLE
Error in `filter-clues` Plugin

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1758]
### Description

Running the following Command:

`./scancode -clp --json-pp sample_filter_clues.json samples --filter-clues`

Gives the Error:

```
ERROR: failed to run post-scan plugin: filter-clues:
Traceback (most recent call last):
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/scancode/cli.py", line 1033, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/cluecode/plugin_filter_clues.py", line 90, in process_codebase
    filtered = filter_ignorable_resource_clues(resource, rules_by_id)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/cluecode/plugin_filter_clues.py", line 105, in filter_ignorable_resource_clues
    resource.emails = filtered.emails
AttributeError: 'ScannedResource' object has no attribute 'emails'

Scanning done.
Some files failed to scan properly:
ERROR: failed to run post-scan plugin: filter-clues:
Traceback (most recent call last):
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/scancode/cli.py", line 1033, in run_codebase_plugins
    plugin.process_codebase(codebase, **kwargs)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/cluecode/plugin_filter_clues.py", line 90, in process_codebase
    filtered = filter_ignorable_resource_clues(resource, rules_by_id)
  File "/home/ayansm/Desktop/GSoD/scancode-toolkit-versions/scancode-toolkit-3.1.1/src/cluecode/plugin_filter_clues.py", line 105, in filter_ignorable_resource_clues
    resource.emails = filtered.emails
AttributeError: 'ScannedResource' object has no attribute 'emails'
```

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Ubuntu 16.04 LTS
* What version of scancode-toolkit was used to generate the scan file? v3.1.1
* What installation method was used to install/run scancode? Source Download

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra Thanks! can you tell if this also happens in the `develop` branch latest and greatest?

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne Sorry for the delay. Yes, the same error occurs in the develop branch latest.

**Comment by pombredanne** [comment]
Thanks, I am making this as a must have for the next release candidate!

**Comment by Iamshankhadeep** [comment]
@pombredanne Can I work on it?

**Comment by pombredanne** [comment]
@Iamshankhadeep please go for it!

**Comment by Iamshankhadeep** [comment]
@pombredanne how can I solve this? I am not getting any Ideas.

**Comment by Iamshankhadeep** [comment]
@pombredanne can you give me any idea about how to solve it?

**Comment by pombredanne** [comment]
@Iamshankhadeep here are steps:
1. try to reproduce the problem in the most minimal way with a command line invocation of scancode as outlined above, trying to find a few files that make this fail
2. once you have a minimally reproducible problem, create a unit test (that is failing for now) that reproduces the problem. Assert the things that should be there in the results.
3. look at the failure trace and try to understand why this is not working and which places the code may need fixing. 

I can start to help you more easily with 3.  once you have done 1. and 2. :)

**Comment by i-m-vivek** [comment]
hi, I am new to open source. I was looking at some good first issues. Can I work on this?

**Comment by tushar912** [comment]
@AyanSinhaMahapatra @pombredanne is this issue available to work on .If so I would like to work on it.

**Comment by AyanSinhaMahapatra** [comment]
@tushar912 Go ahead! 

As you can see the #1804 added a test reproducing the bug  https://github.com/nexB/scancode-toolkit/pull/1804/files.

See more docs on getting stated and running the tests -> https://scancode-toolkit.readthedocs.io/en/latest/contribute/contrib_dev.html. 

It's failing inside this function https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/plugin_filter_clues.py#L212, you could modify the line in the beginning as `TRACE=True` to generate the logs and see what could possibly go wrong. 

Don't hesitate to ask more specific questions if you are stuck!

**Comment by tushar912** [comment]
@AyanSinhaMahapatra I checked the logs and found that the error is in this line <code>resource.emails = filtered.emails</code>because the resource object does not contain email field.I logged the object 
<code>ScannedResource(path=u'samples/JGroups/EULA', rid=7, pid=4, is_file=True, is_filtered=False, licenses=[OrderedDict([(u'key', u'jboss-eula'), (u'score', 100.0), (u'name', u'JBoss EULA'), (u'short_name', u'JBoss EULA'), (u'category', u'Proprietary Free'), (u'is_exception', False), (u'owner', u'JBoss Community'), (u'homepage_url', None), (u'text_url', u'http://repository.jboss.org/licenses/jbossorg-eula.txt'), (u'reference_url', u'https://enterprise.dejacode.com/urn/urn:dje:license:jboss-eula'), (u'spdx_license_key', None), (u'spdx_url', u''), (u'start_line', 3), (u'end_line', 108), (u'matched_rule', OrderedDict([(u'identifier', u'jboss-eula.LICENSE'), (u'license_expression', u'jboss-eula'), (u'licenses', [u'jboss-eula']), (u'is_license_text', True), (u'is_license_notice', False), (u'is_license_reference', False), (u'is_license_tag', False), (u'matcher', '2-aho'), (u'rule_length', 1264), (u'matched_length', 1264), (u'match_coverage', 100.0), (u'rule_relevance', 100)]))])], license_expressions=[u'jboss-eula'], percentage_of_license_text=98.98, copyrights=[OrderedDict([(u'value', u'Copyright 2006 Red Hat, Inc.'), (u'start_line', 104), (u'end_line', 104)])], holders=[OrderedDict([(u'value', u'Red Hat, Inc.'), (u'start_line', 104), (u'end_line', 104)])], authors=[])
</code>
Clearly it does not contain emails.
In order to resolve this I wanted to check the <code>ScannedResource</code> class but i am unable to find it at <code>commoncode.resource</code>. Can you help me find it.

**Comment by AyanSinhaMahapatra** [comment]
@tushar912 if you look into this function _populate() of class `Resource` here, :- https://github.com/nexB/commoncode/blob/main/src/commoncode/resource.py#L441
You can see `ScannedResource` is the runtime name of a `Resource` `attr` Class. So basically when scancode scans files, it creates a Codebase object (Represents a codebase being scanned), then it populates this codebase with Resource objects, which represent files/directories in that codebase. 

Each resource then essentially has information on the scan, for a file/folder, and any post-scan plugin (like the `filter-clues` plugin) runs after the scan is completed, and so at that time each resource has all the scan data (license/copyright/package/email info) in it. 

These resource attributes are the same as the data that is in a scancode JSON output (plus some more attributes for internal use), i.e. the `resource` in the line [`for resource in codebase.walk()`](https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/plugin_filter_clues.py#L89), is a `Resource` class each.

Look into a JSON result output from scancode, and here there'll be some attributes for each file/folder (i.e. resource),
see [`A sample JSON output for an individual file will look like:`](https://scancode-toolkit.readthedocs.io/en/latest/cli-reference/output-format.html#json-pp-file), these [`licenses`, `emails`] are all resource attributes.

**Comment by tushar912** [comment]
@AyanSinhaMahapatra I have found two problems in the code .
1. The one highlighted in this issue ie <code>'ScannedResource' object has no attribute 'emails'</code> .this can be solved by using <code>hasattr</code> check for all attributes in resource object.
2. Once ,this is solved there is another issue . In https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/plugin_filter_clues.py#L226 . Ignorables is assigned None but the function does not return here so if the next lines are executed 
where <code>ignorables.emails</code> or <code> ignorables.urls</code> is called it throws a <code>None Type has no attribute</code> error .
I am thinking of solving this by removing https://github.com/nexB/scancode-toolkit/blob/develop/src/cluecode/plugin_filter_clues.py#L223 and instead checking for <code>if not license_matches</code> in the <code>collect_ignorables</code> function itself and returning if its none. This way instead of being <code>None </code><code>ignorables</code> will be an object having all attributes empty .

Please tell if my approach is correct.

**Comment by AyanSinhaMahapatra** [comment]
@tushar912 IMHO that sounds correct, please go ahead and see if that passes the test reproducing the bug. Thanks++
