### ISSUE TITLE
interrupt while scanning with python cli

### ISSUE THREAD

**Issue by Angi2412** [nexB/scancode-toolkit#1845]
### Description
Sometimes when i scan certain packages e.g. openssl source code i get following error:

>  Unhandled exception in thread started by <function interruptible.<locals>.runner at 0x10FA5108>
> Traceback (most recent call last):
>   File "C:\Users\y509019\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scancode\interrupt.py", line 145, in runner
>     results.put((ERROR_MSG + traceback_format_exc(), NO_VALUE,))
> Exception

i use the following cli command via python to scan:
```
rc, results = cli.run_scan(
            path, license=True, copyright=True,
            return_results=True, max_in_memory=500000, processes=8,
            verbose=True, quiet=False, timeout=360000
        )
```
where "path" is the path of the source code folder.
Unfortunately does scancode not provide part results - instead it gets stuck when the exception occours.
### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? Windows10
* What version of scancode-toolkit was used to generate the scan file? latest cli.py from developer branch
* What installation method was used to install/run scancode? import via python

**Comment by pombredanne** [comment]
@Angi2412 Thank you for this detailed report!

> Sometimes when i scan certain packages e.g. openssl source code i get following error:

Is this happening all the times? Do you have a URL for a public package where this happened?
What are the specs of your machine (CPU, RAM)?

>  Unfortunately does scancode not provide part results - instead it gets stuck when the exception occours. 

Would you have a more complete or full stack trace available?

Note that this kind of things are sometimes hard to debug: one way to simplify the problem is to disable multiprocessing and multithreading entirely as well as disable on-disk caching, to rule out issues in these areas and get a better error message.

So in your case this would be this:
```
rc, results = cli.run_scan(
            path, license=True, copyright=True,
            return_results=True, max_in_memory=0, processes=-1,
            verbose=True, quiet=False
        )
```

Could you try to run this on your faulty scans as you may get a better error message?

Side note: I do not think you would need such a long time out ... 36000 seconds means 10 hours and sounds very long! Why do you use this?

**Comment by pombredanne** [comment]
Actually your timeout is 360,000 seconds... meaning 100 hours.

**Comment by Angi2412** [comment]
@pombredanne Thank you for your fast response.


> Is this happening all the time?

No, it does not happen all the time, only with certain archives - but with these all the time.

> Do you have a URL for a public package where this happened?

I don't think so - but I will take a look.

> What are the specs of your machine (CPU, RAM)?

It's a mobile eight-generation i7 with 16gb of ram in a dell notebook

> Would you have a more complete or full stack trace available?
> Could you try to run this on your faulty scans as you may get a better error message?

I will try your suggested command on Friday at work. Then I will provide a full stack trace.

> I do not think you would need such a long time out [...] Why do you use this?

I only set the timeout that high, that there would be no possibility to interrupt a scan because of timeout limitations. Is there a disadvantage to using such a high timeout?

**Comment by Angi2412** [comment]
@pombredanne 
I tried your suggested command. Then scancode stopped when it should scan a .tar file (see screenshot).
![debug console](https://user-images.githubusercontent.com/11177877/69864334-f43d1d00-129e-11ea-8596-43fd255df71d.png)

But this .tar file wasn't supposed to be there - because of this i found out, that our extraction script had a bug. I fixed the bug - now all archives are extracted before scancode starts a scan. Then your suggested command worked. After that i changed "processor" to 10 - and it still works. 
So, i think that was the problem. 

Still i would suggest that when scancode comes to an archive it should just skip it instead of aborting the whole scan without part results.

**Comment by pombredanne** [comment]
@Angi2412 Thank you for following up!

> I only set the timeout that high, that there would be no possibility to interrupt a scan because of timeout limitations. Is there a disadvantage to using such a high timeout?

You can use 0 instead to disable any timeout. But did you have issues with timeouts to set such a high one? Generally you should avoid using a --timeout option except for special cases. 

Also using a very long or 0 timeout will effectively make scancode wait forever until a scans complete for each file, which could be a bug or a very large or a large file with a very large number of licenses and copyrights. 
This long timeout could very well be the cause of your problem (as this would be perceived as if scancode was hanging)


A few other things:
1. you could use the `extractcode` command which part of scancode to extract things. This is a nifty and mostly universal and recursive archive extractor... but that will not solve your problem.

2. this tarball should not make Scancode choke. What is special about it? some permission issue? some size issues? How big is it? What happens when you run a scan from the command line instead of through your web app, and for this test without a timeout argument?

And also did it really crashed or hang? or just reported an error on that single file?
That would be an important difference. If it hangs that's a serious bug,

3. side note: you seem to have a nice Flask app that uses scancode! :bow: ... do not hesitate to share this if this is possible!

**Comment by Angi2412** [comment]
> You can use 0 instead to disable any timeout. But did you have issues with timeouts to set such a high one?

No, i did not have any issues. Using such a high timeout was just a 
preventive action.

> And also did it really crashed or hang? or just reported an error on that single file?
It just reported an error on that single file but did not give a resulting json file.

For me the problem does not occur again so far... 

> side note: you seem to have a nice Flask app that uses scancode! 🙇 ... do not hesitate to share this if this is possible!

The application is still in internal Development. I don't know if it will be available for the public ... if this will be the case, i will inform you

Thanks again, for the fast responses :)

**Comment by pombredanne** [comment]
@Angi2412 re:

> No, i did not have any issues. Using such a high timeout was just a preventive action.

IMHO you will be best leaving this out for now. Having not too long a timeout is a preventive measure so you were effectively defeating that and that would be a good reason for the issue you have faced.

> Thanks again, for the fast responses :)

sure thing: any time. And thank you for using Scancode!
