### ISSUE TITLE
Confusing license 'ps-or-pdf-font-exception-20170817'

### ISSUE THREAD

**Issue by qduanmu** [nexB/scancode-toolkit#1976]
### Description
The license ['ps-or-pdf-font-exception-20170817'](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/ps-or-pdf-font-exception-20170817.LICENSE) states that it is the GNU Affero license, but the identifier "ps-or-pdf-font-exception-20170817" makes me think that it *not* a license but an exception to the license. Related SPDX link for this license is [here](https://spdx.org/licenses/PS-or-PDF-font-exception-20170817.html).

Should we update the license text to something below, and add rules with identifier like 'agpl-3.0_with_ps-or-pdf-font-exception'?
> As a special exception, permission is granted to include these font programs in a Postscript or PDF file that consists of a document that contains text to be displayed or printed using this font, regardless of the conditions or license applying to the document Itself.

**Comment by darkdebo** [comment]
Can I work on it

**Comment by sutula** [comment]
@darkdebo, do you have a preferred direction on this issue?  Do you plan to change the name of the license type to include "affero", or do you plan to leave the name and trim the matched text to include only the exception portion?

As input, I would prefer the second option, leaving the name alone and trimming the matched text to be only the exception portion.  Then scancode would report both affero and ps-or-pdf-font-exception-20170817.

**Comment by qduanmu** [comment]
Hi @pombredanne , any opinion on this please?

**Comment by pombredanne** [comment]
@qduanmu @sutula sorry for the late reply!

Here is my take: the license should not include this notice:

> The font and related files in this directory are distributed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3 (see the file COPYING), with
the following exemption: 

This is an Affero GPL notice of its own
So I agree with you and I suggest these:
1. remove that part from the standard text for this exception such that if is ever seen alone it is detected alone
2. add a rule that combine both and return the expression `agpl-3.0 WITH ps-or-pdf-font-exception-20170817` so that when both are present they are both detected together .
3. add more rules like in 2 based on a scan and detailed review of https://github.com/ArtifexSoftware/urw-base35-fonts and possibly other Artifex projects for sanity

**Comment by qduanmu** [comment]
@pombredanne , thank you. Hi, @darkdebo , will you work on this?

**Comment by pombredanne** [comment]
@qduanmu I have a fix in a branch that I will push tomorrow at the latest ;)

**Comment by pombredanne** [comment]
This has long been merged and released. Closing. Happy new year!
