### ISSUE TITLE
Add license detection rules for https://licensebuttons.net/

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#1983]
## Short Description
https://licensebuttons.net/ contains several buttons to CC licenses that are found as links often enough.
For instance https://licensebuttons.net/p/80x15.png or https://licensebuttons.net/l/GPL/2.0/88x62.png
Each such URL should be added as a license detection rule

## Possible Labels

- new feature

## Select Category

-  Enhancement [x]
-  Add License/Copyright [x]
-  Scan Feature []
-  Packaging []
-  Documentation []
-  Expand Support []
-  Other []

**Comment by MankaranSingh** [comment]
All these would be considered as 'license reference', right ?

**Comment by MankaranSingh** [comment]
I tried to add this as a license rule "https://licensebuttons.net/l/GPL/2.0/{{88x62.png}}" since they may add new resolutions or formats later. But this doesn't seem to work when i change the resolution or format in test file. 

Also, See this https://licensebuttons.net/l/by-nc-nd/2.5/
It has a lot of sub folders according to region, so should i just add "https://licensebuttons.net/l/by-nc-nd/2.5/" as a licence rule (which also solves the above problem) ?

**Comment by pombredanne** [comment]
> All these would be considered as 'license reference', right ?

Yes these are references... 

Also, there is no such thing as curly braces to abstract parts such as in `{{}}`
Instead of `https://licensebuttons.net/l/GPL/2.0/{{88x62.png}}` just craft eventually two rules:
- `https://licensebuttons.net/l/GPL/2.0/88x62.png`
- `https://licensebuttons.net/l/GPL/2.0/`

> Also, See this https://licensebuttons.net/l/by-nc-nd/2.5/
> It has a lot of sub folders according to region, so should i just add "https://licensebuttons.net/l/by-nc-nd/2.5/" as a licence rule (which also solves the above problem) ?

yes that's an excellent approach! :+1:
