### ISSUE TITLE
other-permissive includes references to now-defunct visualidiot.com

### ISSUE THREAD

**Issue by sutula** [nexB/scancode-toolkit#1999]
### Description

https://github.com/nexB/scancode-toolkit/issues/960 added three rules related to the visualidiot license.  Since that time, the referenced website has changed such that the license isn't visible any more.  It may be that the domain has changed hands or that the original author uses these references for publicity or click-bait.  In any case, I would take issue with continuing to characterize the following three rules as "permissive":

- other-permissive_12
- other-permissive_13
- other-permissive_14

Note that the rule source code includes [a web archive URL](https://web.archive.org/web/20120502165504/http://licence.visualidiot.com/) which still lists the original contents of the referenced URL.

If this text still exists in code, then it is still worthwhile to detect it.  Rather than simply removing these rules, can we move them to a license type that reflects that they are not necessarily benign permissive texts, but that would require some amount of legal scrutiny before code licensed under these texts could be utilized, if it could be used at all?

### How To Reproduce

This issue relates to how certain license texts are characterized/categorized.  The issue isn't so much reproduced as seen by inspection of the underlying license rules.  The following source files are involved:

- src/licensedcode/data/rules/other-permissive_12.RULE
- src/licensedcode/data/rules/other-permissive_12.yml
- src/licensedcode/data/rules/other-permissive_13.RULE
- src/licensedcode/data/rules/other-permissive_13.yml
- src/licensedcode/data/rules/other-permissive_14.RULE
- src/licensedcode/data/rules/other-permissive_14.yml

### System configuration

This issue is independent of system configuration.

### Offer of Help

I'd be happy to submit a patch for this change, but would like to hear suggestions for a new license category home for the visualidiot license.  If there seems to be an existing category that would fit, let's re-use it.  Otherwise, I suggest a new license type for this one.

**Comment by pombredanne** [comment]
@sutula good catch! And thank you for this. Your suggestion to add a new license for that makes the most sense to me, even if this a legacy license of sorts there are still enough examples of this https://github.com/search?q=%22persons%2C+or+any+similar+actions+percolating+the+given+%22&type=Code

This would be best qualified as some kind of proprietary license e.g. using the "Proprietary Free" category. We can always change the category afterwards too, but IMHO the combo of a license key of `visual-idiot` with a `Proprietary Free` would be enough of a warning this is a problematic thing.

So in recap we could:
1. create a new license
2. requalify the detected license for the existing rules

A patch would be great and I am on hand to help as needed.

 @DennisClark this is the problematic text FWIW, which makes me cringe rather than smile. 

> By attaching this document to the given files (the “work”), you, the licensee,
are hereby granted free usage in both personal and commerical environments,
without any obligation of attribution or payment (monetary or otherwise).
> 
> The licensee is free to use, copy, modify, publish, distribute, sublicence,
and/or merchandise the work, subject to the licensee inflecting a positive
message unto someone.
> 
> This includes (but is not limited to): smiling, being nice, saying “thank you”,
assisting other persons, or any similar actions percolating the given concept.
> 
> The above copyright notice serves as a permissions notice also, and may
optionally be included in copies or portions of the work.

> The work is provided “as is”, without warranty or support, express or implied.
> The author(s) are not liable for any damages, misuse, or other claim, whether
from or as a consequence of usage of the given work.
