### ISSUE TITLE
Parse Gemspec Files

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#2035]
This is apart of GSoC 2020 phase 1. 

We need to add the ability to parse `.gemspec` files and have them apart of a `--package` scan.

**Comment by rpotter12** [comment]
@majurg @pombredanne
https://gitlab.com/balasankarc/gemfileparser library is definitely in more robust way but it extract only dependencies from the gemspec file and not from all file like it does not give any output for https://github.com/nexB/scancode-toolkit/blob/develop/tests/packagedcode/data/rubygems/gemspec/address_standardization.gemspec , This library totally needs to be changed to extract all the data and even dependencies too because it is not even extracting dependencies properly from every file like when dependencies are in the form `add_development_dependency "mechanize", ">=0.4"` it will extract the data but when the dependencies are in the form `s.add_dependency(%q<mechanize>, [">= 0"])` it will not extract data.

**Comment by majurg** [comment]
@rpotter12 What are the specifics that need to be changed in that particular library? Or what are the limitations? Please be specific here as we are not privy to the details. 

Additionally, does your code handle those particular different ways of describing dependencies and do we have a test case for this?

**Comment by rpotter12** [comment]
Sample gemspec file:
```
# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mysmallidea-address_standardization}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Elliot Winkler"]
  s.date = %q{2010-02-01}
  s.description = %q{A tiny Ruby library to quickly standardize a postal address}
  s.email = %q{elliot.winkler@gmail.com}
  s.extra_rdoc_files = [
    "README.md",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "README.md",
     "Rakefile",
     "TODO",
     "address_standardization.gemspec",
     "lib/address_standardization.rb",
     "lib/address_standardization/abstract_service.rb",
     "lib/address_standardization/address.rb",
     "lib/address_standardization/class_level_inheritable_attributes.rb",
     "lib/address_standardization/google_maps.rb",
     "lib/address_standardization/melissa_data.rb",
     "lib/address_standardization/ruby_ext.rb",
     "lib/address_standardization/version.rb",
     "test/google_maps_test.rb",
     "test/melissa_data_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mcmire/address_standardization}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A tiny Ruby library to quickly standardize a postal address}
  s.test_files = [
    "test/google_maps_test.rb",
     "test/melissa_data_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
      s.add_development_dependency(%q<mcmire-context>, [">= 0"])
      s.add_development_dependency(%q<mcmire-matchy>, [">= 0"])
    else
      s.add_dependency(%q<mechanize>, [">= 0"])
      s.add_dependency(%q<mcmire-context>, [">= 0"])
      s.add_dependency(%q<mcmire-matchy>, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 0"])
    s.add_dependency(%q<mcmire-context>, [">= 0"])
    s.add_dependency(%q<mcmire-matchy>, [">= 0"])
  end
end
```
From https://gitlab.com/balasankarc/gemfileparser library we can only extract dependencies. But when we parse this sample gemspec file from this parser we will not get name of any dependency because it is in the other form then the general form.

Ans this gemspec file is also having other important data like name, version, description, authors, email, etc which is not extracted by https://gitlab.com/balasankarc/gemfileparser library. So I have edited these codes and create a complete parser for gemspec file and added tests too in the PR.

PR link: https://github.com/nexB/scancode-toolkit/pull/2075
