### ISSUE TITLE
Remove link checks from CI

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#2101]
### Description

There are too many random failures on link checks done in the Travis CI. We should remove these and make them something else that does not break the build for no good reason.
See https://github.com/nexB/scancode-toolkit/pull/1835/commits/e0f1b4fd1b00abb581832d79d790b847c5eb4ff1 for the last commit with some link checks.

@AyanSinhaMahapatra FYI

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne I never thought this would cause so much trouble though, apologies for the trouble caused.

These fails are inherently caused by network issues, and not the tools itself (I think?) so it seems there's no way to test for links, without these random errors creeping up, it's obviously just better to not have these tests than having the CI testing throwing errors everywhere. But I'll check if this can be done some other way, and update here. 

So you've already removed these in the linked commit I think? So anything else you need me to look into?

**Comment by pombredanne** [comment]
>I never thought this would cause so much trouble though, apologies for the trouble caused.

No worries and no need for apologies! and yes failures are network-related or transient site availability or else.

> So you've already removed these in the linked commit I think? 

yes,

> So anything else you need me to look into?

 we should see if a pre-commit hook may be a better solution?

**Comment by pombredanne** [comment]
Closing for now
