### ISSUE TITLE
Have no idea what input to pass

### ISSUE THREAD

**Issue by S3j5b0** [nexB/scancode-toolkit#2492]
Hi, I'm trying to use scancode to scan o project.

Typing scancode --help gets me this format:
`scancode [OPTIONS] <OUTPUT FORMAT OPTION(s)> <input>...`

So i try passing my input directory in:

`scancode -ic devops-21/`

This however gives me:

'Error: Missing output option(s): at least one output option is required to save scan results.'

ok, cool, I should add an output option:
`scancode -ic devops-21/ output.html`
This however gives me this error

`Invalid value for "input": Path "output.html" does not exist.`

Which is really weird, why does it now interpret output.html as the input file? 
How do I make the scan? a minimal working example would be really nice

**Comment by AyanSinhaMahapatra** [comment]
@S3j5b0 you're missing the output format option before the output. Also, you should use JSON as output and use [scancode-workbench to visualize](https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_visualize_scan_results.html), as HTML is deprecated now.

So, your scan should have been `scancode -ic devops-21/ --json-pp outut.json` for the same command as you mentioned above. 

Use more options to scan for more things, see docs at [scan example](https://scancode-toolkit.readthedocs.io/en/latest/tutorials/how_to_run_a_scan.html#running-the-scan) and [all CLI options](https://scancode-toolkit.readthedocs.io/en/latest/cli-reference/) for more details.

It's also best to ask these kind of questions in our [gitter chat](https://gitter.im/aboutcode-org/scancode) rather than opening an issue.

**Comment by AyanSinhaMahapatra** [comment]
This was a problem with providing the CLI options correctly and is documented in the docs clearly, with examples. From https://github.com/nexB/scancode-toolkit/issues/2495#issue-857259090 we see that you've run a scan correctly so closing this.
