### ISSUE TITLE
False positive for utils-merge:1.0.1

### ISSUE THREAD

**Issue by hanna-modica** [nexB/scancode-toolkit#2523]
### Description

ScanCode 3.2.1-rc2 report the lines 21-24 at https://github.com/jaredhanson/utils-merge/blob/v1.0.1/package.json as MIT or GPL-2.0-only which is a false-positive, since it is only MIT.

### How To Reproduce

Scan https://github.com/jaredhanson/utils-merge/tree/v1.0.1

### System configuration

The scan was done on Linux with the OSS Review Toolkit https://github.com/oss-review-toolkit/ort/ using ScanCode as the scanner.

**Comment by pombredanne** [comment]
@hanna-modica Thank you for the report!
That's a great catch as the license data in https://github.com/jaredhanson/utils-merge/blob/v1.0.1/package.json is both non-standard and definitely a bug on scancde's side

**Comment by pombredanne** [comment]
For reference this is the JSON output for a --package and --license scan.
Interestingly, the file-level license detection (where the package.json is treated as plain text) is incorrect, but the package manifest license detection (where the package.json is treated as an npm package manifest with a well known structure) is correct. 

```JSON
{
  "headers": [
    {
      "tool_name": "scancode-toolkit",
      "tool_version": "21.3.31",
      "options": {
        "input": [
          "package.json"
        ],
        "--json-pp": "-",
        "--license": true,
        "--license-text": true,
        "--license-text-diagnostics": true,
        "--package": true
      },
      "notice": "Generated with ScanCode and provided on an \"AS IS\" BASIS, WITHOUT WARRANTIES\nOR CONDITIONS OF ANY KIND, either express or implied. No content created from\nScanCode should be considered or used as legal advice. Consult an Attorney\nfor any legal advice.\nScanCode is a free software code scanning tool from nexB Inc. and others.\nVisit https://github.com/nexB/scancode-toolkit/ for support and download.",
      "start_timestamp": "2021-05-18T070822.890322",
      "end_timestamp": "2021-05-18T070828.986493",
      "duration": 6.096200466156006,
      "message": null,
      "errors": [],
      "extra_data": {
        "files_count": 1
      }
    }
  ],
  "files": [
    {
      "path": "package.json",
      "type": "file",
      "licenses": [
        {
          "key": "mit",
          "score": 100.0,
          "name": "MIT License",
          "short_name": "MIT License",
          "category": "Permissive",
          "is_exception": false,
          "owner": "MIT",
          "homepage_url": "http://opensource.org/licenses/mit-license.php",
          "text_url": "http://opensource.org/licenses/mit-license.php",
          "reference_url": "https://scancode-licensedb.aboutcode.org/mit",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.yml",
          "spdx_license_key": "MIT",
          "spdx_url": "https://spdx.org/licenses/MIT",
          "start_line": 20,
          "end_line": 20,
          "matched_rule": {
            "identifier": "mit_30.RULE",
            "license_expression": "mit",
            "licenses": [
              "mit"
            ],
            "is_license_text": false,
            "is_license_notice": false,
            "is_license_reference": false,
            "is_license_tag": true,
            "is_license_intro": false,
            "matcher": "2-aho",
            "rule_length": 2,
            "matched_length": 2,
            "match_coverage": 100.0,
            "rule_relevance": 100
          },
          "matched_text": "license\": \"MIT\","
        },
        {
          "key": "mit",
          "score": 16.67,
          "name": "MIT License",
          "short_name": "MIT License",
          "category": "Permissive",
          "is_exception": false,
          "owner": "MIT",
          "homepage_url": "http://opensource.org/licenses/mit-license.php",
          "text_url": "http://opensource.org/licenses/mit-license.php",
          "reference_url": "https://scancode-licensedb.aboutcode.org/mit",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/mit.yml",
          "spdx_license_key": "MIT",
          "spdx_url": "https://spdx.org/licenses/MIT",
          "start_line": 21,
          "end_line": 24,
          "matched_rule": {
            "identifier": "mit_or_gpl-2.0_46.RULE",
            "license_expression": "mit OR gpl-2.0",
            "licenses": [
              "mit",
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "3-seq",
            "rule_length": 36,
            "matched_length": 6,
            "match_coverage": 16.67,
            "rule_relevance": 100
          },
          "matched_text": "licenses\": [\n    {\n      \"[type]\": \"[MIT]\",\n      \"[url]\": \"http://opensource.org/licenses/MIT\""
        },
        {
          "key": "gpl-2.0",
          "score": 16.67,
          "name": "GNU General Public License 2.0",
          "short_name": "GPL 2.0",
          "category": "Copyleft",
          "is_exception": false,
          "owner": "Free Software Foundation (FSF)",
          "homepage_url": "http://www.gnu.org/licenses/gpl-2.0.html",
          "text_url": "http://www.gnu.org/licenses/gpl-2.0.txt",
          "reference_url": "https://scancode-licensedb.aboutcode.org/gpl-2.0",
          "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/gpl-2.0.LICENSE",
          "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/gpl-2.0.yml",
          "spdx_license_key": "GPL-2.0-only",
          "spdx_url": "https://spdx.org/licenses/GPL-2.0-only",
          "start_line": 21,
          "end_line": 24,
          "matched_rule": {
            "identifier": "mit_or_gpl-2.0_46.RULE",
            "license_expression": "mit OR gpl-2.0",
            "licenses": [
              "mit",
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "3-seq",
            "rule_length": 36,
            "matched_length": 6,
            "match_coverage": 16.67,
            "rule_relevance": 100
          },
          "matched_text": "licenses\": [\n    {\n      \"[type]\": \"[MIT]\",\n      \"[url]\": \"http://opensource.org/licenses/MIT\""
        }
      ],
      "license_expressions": [
        "mit",
        "mit OR gpl-2.0"
      ],
      "percentage_of_license_text": 8.51,
      "packages": [
        {
          "type": "npm",
          "namespace": null,
          "name": "utils-merge",
          "version": "1.0.1",
          "qualifiers": {},
          "subpath": null,
          "primary_language": "JavaScript",
          "description": "merge() utility function",
          "release_date": null,
          "parties": [
            {
              "type": "person",
              "role": "author",
              "name": "Jared Hanson",
              "email": "jaredhanson@gmail.com",
              "url": "http://www.jaredhanson.net/"
            }
          ],
          "keywords": [
            "util"
          ],
          "homepage_url": null,
          "download_url": "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz",
          "size": null,
          "sha1": null,
          "md5": null,
          "sha256": null,
          "sha512": null,
          "bug_tracking_url": "http://github.com/jaredhanson/utils-merge/issues",
          "code_view_url": null,
          "vcs_url": "git://github.com/jaredhanson/utils-merge.git",
          "copyright": null,
          "license_expression": "mit",
          "declared_license": [
            "MIT",
            {
              "type": "MIT",
              "url": "http://opensource.org/licenses/MIT"
            }
          ],
          "notice_text": null,
          "root_path": null,
          "dependencies": [
            {
              "purl": "pkg:npm/make-node",
              "requirement": "0.3.x",
              "scope": "devDependencies",
              "is_runtime": false,
              "is_optional": true,
              "is_resolved": false
            },
            {
              "purl": "pkg:npm/mocha",
              "requirement": "1.x.x",
              "scope": "devDependencies",
              "is_runtime": false,
              "is_optional": true,
              "is_resolved": false
            },
            {
              "purl": "pkg:npm/chai",
              "requirement": "1.x.x",
              "scope": "devDependencies",
              "is_runtime": false,
              "is_optional": true,
              "is_resolved": false
            }
          ],
          "contains_source_code": null,
          "source_packages": [],
          "purl": "pkg:npm/utils-merge@1.0.1",
          "repository_homepage_url": "https://www.npmjs.com/package/utils-merge",
          "repository_download_url": "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz",
          "api_data_url": "https://registry.npmjs.org/utils-merge/1.0.1"
        }
      ],
      "scan_errors": []
    }
  ]
}

```

**Comment by pombredanne** [comment]
@hanna-modica do you want to try to fix this by chance? I can provide you with detailed guidance.

**Comment by hanna-modica** [comment]
Hi @pombredanne,
thank you for your fast response and your kind offer. I have never worked on the ScanCode project before, but if you are saying it can be done, I can try to do it tomorrow morning. After that I will be leaving my laptop for a week.

**Comment by pombredanne** [comment]
@hanna-modica here would be how I would solve it.

**A. running with the options `scancode --license --license-text --license-text-diagnostics --json-pp - package.json` as above, I can see these interesting details in the JSON:**
```
          "start_line": 21,
          "end_line": 24,
          "matched_rule": {
            "identifier": "mit_or_gpl-2.0_46.RULE",
            "license_expression": "mit OR gpl-2.0",
            "licenses": [
              "mit",
              "gpl-2.0"
            ],
            "is_license_text": false,
            "is_license_notice": true,
            "is_license_reference": false,
            "is_license_tag": false,
            "is_license_intro": false,
            "matcher": "3-seq",
            "rule_length": 36,
            "matched_length": 6,
            "match_coverage": 16.67,
            "rule_relevance": 100
          },
          "matched_text": "licenses\": [\n    {\n      \"[type]\": \"[MIT]\",\n      \"[url]\": \"http://opensource.org/licenses/MIT\""
```

**B. The rule that was matched is "mit_or_gpl-2.0_46.RULE" which can be found in these two files:**
  - https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/src/licensedcode/data/rules/mit_or_gpl-2.0_46.RULE
  - https://github.com/nexB/scancode-toolkit/blob/bb044200ae86770f9bb01560c0033037ee18b947/src/licensedcode/data/rules/mit_or_gpl-2.0_46.yml

**C. The `mit_or_gpl-2.0_46.RULE` has this text:**
```
Dual licensed under the MIT or GPL licenses:
[http://opensource.org/licenses/MIT](http://opensource.org/licenses/MIT)
[http://www.gnu.org/licenses/gpl-2.0.html](http://www.gnu.org/licenses/gpl-2.0.html)
```

**D. The `package.json` section of interest is this:**
```
  "license": "MIT",
  "licenses": [
    {
      "type": "MIT",
      "url": "http://opensource.org/licenses/MIT"
```
 and these are two "tags" with references to the MIT license 


**E. The JSON scan results "matched_text" shows us** the exact matched text with parts not matched enclosed in [square brackets] (that's what the --license-text-diagnotics does)

> "matched_text": "licenses\": [\n    {\n      \"[type]\": \"[MIT]\",\n      \"[url]\": \"http://opensource.org/licenses/MIT\""

And these details:
- `"matched_length": 6` tells that only 6 words were matched
- `"match_coverage": 16.67` tells that the match is only matching 16.67% of the rule words e.g. 6/36 (because `"rule_length": 36` words)

**F. Therefore there are two issues:**

**1. This text should be matched exactly to an MIT**  and not some MIT or GPL rule
> licenses": [
>    {
      "type": "MIT",
      "url": "http://opensource.org/licenses/MIT"

**2. The rule `mit_or_gpl-2.0_46.RULE` should not be matched with so few words matching** (only 6/36).


**For 1. the solution is to create a new rule with these two files** in https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules (the file names are arbitrary and have no special meaning... as long as they are unique. By convention we use the detected licenses in the names)
- `mit_in_npm_1.RULE` with this text (note that scancode ignore punctuation and formatting):  
```
licenses": 
"type": "MIT",
"url": "http://opensource.org/licenses/MIT"
```
- `mit_in_npm_1.yml` with this text:  
```
license_expression: mit
is_license_tag: yes
relevance: 100
ignorable_urls:
    - http://opensource.org/licenses/MIT
```
**... which means that:**
- the .RULE corresponds to the `mit` license expression when detected. 
- its text is for a license tag, e.g. some typically short but structured and highly relevant license information (here a license tag in a package.json)
- even though this is short, this 100% relevant
- it contains a URL to http://opensource.org/licenses/MIT which can be optionally ignored from URL detection when using the `--filter-clues` option to avoid reporting a URL when this is already part of a license detection.
 
**For 2. we want to tell that  `mit_or_gpl-2.0_46.RULE`  should only be reported** if say about 60% of its words were matched. Otherwise this is not enough of a match (and do not worry as there are plenty of smaller rules that would catch this otherwise)
Edit  `mit_or_gpl-2.0_46.yml` to add a `minimum_coverage: 60` to that effect which would look this way afterwards:
```
license_expression: mit OR gpl-2.0
is_license_notice: yes
relevance: 100
ignorable_urls:
    - http://opensource.org/licenses/MIT
    - http://www.gnu.org/licenses/gpl-2.0.html
minimum_coverage: 60
```

**Finally you want to add a test to ensure that we will not get any regression.**
For this add a pair of files in https://github.com/nexB/scancode-toolkit/tree/develop/tests/licensedcode/data/datadriven/lic4 which will be picked up automatically as a new "data-driven" test entry.
(here too the file names are arbitrary and have no special meaning... as long as they are unique.)
- `2523-utils-merge_package.json` with the content of the file at https://github.com/jaredhanson/utils-merge/blob/v1.0.1/package.json
- `2523-utils-merge_package.json.yml` with this content:
```
license_expressions:
  - mit
  - mit
notes: Based on https://raw.githubusercontent.com/jaredhanson/utils-merge/v1.0.1/package.json
```

... which means that when scanning `2523-utils-merge_package.json` there should be two MIT detected here so we expect these in the list of  `license_expressions`. The notes are informational and optional, `2523-utils-merge_package.json` is a made up name based on the issue number and the original file name. 

Do not hesitate to ask plenty questions. And if you do not feel comfy doing it no worries, do not feel obligated to do anything.

**Comment by hanna-modica** [comment]
Hi @pombredanne,

thank you very much for your very detailed and comprehensive explanations. I was able to follow them and already committed the changes on a local branch, but I cannot push my branch to origin, because I receive a 403. Do I need special rights?

**Comment by AyanSinhaMahapatra** [comment]
Thanks! @hanna-modica 

Could you fork the repo, clone locally, do the changes, push it to the fork and then create a PR here from your fork?

And repeating what @pombredanne said,

> And if you do not feel comfy doing it no worries, do not feel obligated to do anything.

**Comment by hanna-modica** [comment]
Hi @pombredanne and @AyanSinhaMahapatra,

thank you very much for your guidance. I have opened a PR [here](https://github.com/nexB/scancode-toolkit/pull/2537)

Can you access it or do I have to give you somehow permissions?

**Comment by sschuberth** [comment]
> Can you access it or do I have to give you somehow permissions?

No special permissions are required, @hanna-modica 😉
