### ISSUE TITLE
Implement an option for shallow extraction

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#262]
Currect `extractcode` does not have an option for shallow extraction.

**Comment by pombredanne** [comment]
This makes a lot of sense. Especially since this is already supported internally.
As you can see in https://github.com/nexB/scancode-toolkit/blob/e45f8f401ca22a15fda6a78dff317e8acf94038e/src/extractcode/extract.py#L97 the function has a `recurse` argument which defaults to `False` but is set to True when called from the `extractcode` CLI

**Comment by majurg** [comment]
Ive implemented this feature and its working as intended. Any feedback is appreciated.

**Comment by pombredanne** [comment]
Thanks! The code looks fine. Would you mind adding some tests? Especially for the case where you ran a shallow extraction once and run it again: are archives extracted from top level archives extracted further one level down? 
You might want to refine the help text for the CLi option too. `Extract top level archives only.` may not be super self explanatory?

**Comment by pombredanne** [comment]
Also I wonder if `recurse` may be better than `shallow` ? though I am not too sure.

**Comment by majurg** [comment]
I was thinking about that too, but did not necessarily want to change the default behavior as it has been up to now.

**Comment by majurg** [comment]
Currently, archives are not extracted after running `extractcode --shallow` twice on the same directory. It has something to do with the way the `-extract` directory is created. 

It appears that the `archive.tgz-extract` directory gets created again or overwritten when `extractcode --shallow` is run a second time, and the previously nested archives do not get extracted.

If I were to change the name of the extracted directory to something else, the command works as expected. 

My guess is the problem lies in the order that pathnames/files are processed during extract events

**Comment by pombredanne** [comment]
This has been merged in develop. @chinyeungli @majurg Thanks you!
