### ISSUE TITLE
"X11 License" wrongly matched to spdx_license_key "ICU"

### ISSUE THREAD

**Issue by yunhua-deng** [nexB/scancode-toolkit#2672]
### Description

"X11 License" wrongly matched to spdx_license_key "ICU"

```json
{
  "path": "apache-ftpserver-1.1.1/src/distribution/LICENSE.slf4j.txt",
  "type": "file",
  "name": "LICENSE.slf4j.txt",
  "base_name": "LICENSE.slf4j",
  "extension": ".txt",
  "size": 1482,
  "date": "2017-04-15",
  "sha1": "f1aaa5f4c290ad7226ca9b25fa055357e531e312",
  "md5": "6d1ccb2d228a207664178f6e231cbd45",
  "sha256": "0ab2311627fb506c44c80723c845644bc2f1bdeb77327a6a94395908104cfeed",
  "mime_type": "text/plain",
  "file_type": "ASCII text",
  "programming_language": null,
  "is_binary": false,
  "is_text": true,
  "is_archive": false,
  "is_media": false,
  "is_source": false,
  "is_script": false,
  "licenses": [
    {
      "key": "x11",
      "score": 100.0,
      "name": "X11 License",
      "short_name": "X11 License",
      "category": "Permissive",
      "is_exception": false,
      "owner": "XFree86 Project, Inc",
      "homepage_url": "http://www.xfree86.org/3.3.6/COPYRIGHT2.html",
      "text_url": "http://www.xfree86.org/3.3.6/COPYRIGHT2.html",
      "reference_url": "https://scancode-licensedb.aboutcode.org/x11",
      "scancode_text_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/x11.LICENSE",
      "scancode_data_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/x11.yml",
      "spdx_license_key": "ICU",
      "spdx_url": "https://spdx.org/licenses/ICU",
      "start_line": 4,
      "end_line": 27,
      "matched_rule": {
        "identifier": "x11.LICENSE",
        "license_expression": "x11",
        "licenses": [
          "x11"
        ],
        "is_license_text": true,
        "is_license_notice": false,
        "is_license_reference": false,
        "is_license_tag": false,
        "is_license_intro": false,
        "matcher": "2-aho",
        "rule_length": 225,
        "matched_length": 225,
        "match_coverage": 100.0,
        "rule_relevance": 100
      },
      "matched_text": "Permission is hereby granted, free of charge, to any person obtaining\na copy of this software and associated documentation files (the\n\"Software\"), to deal in the Software without restriction, including\nwithout limitation the rights to use, copy, modify, merge, publish,\ndistribute, and/or sell copies of the Software, and to permit persons\nto whom the Software is furnished to do so, provided that the above\ncopyright notice(s) and this permission notice appear in all copies of\nthe Software and that both the above copyright notice(s) and this\npermission notice appear in supporting documentation.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\nMERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\nOF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR\nHOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY\nSPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER\nRESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF\nCONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN\nCONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.\n\nExcept as contained in this notice, the name of a copyright holder\nshall not be used in advertising or otherwise to promote the sale, use\nor other dealings in this Software without prior written authorization\nof the copyright holder."
    }
  ],
  "license_expressions": [
    "x11"
  ],
  "percentage_of_license_text": 96.15,
  "copyrights": [
    {
      "value": "Copyright (c) 2004-2007 QOS.ch",
      "start_line": 1,
      "end_line": 1
    }
  ],
  "holders": [
    {
      "value": "QOS.ch",
      "start_line": 1,
      "end_line": 1
    }
  ],
  "authors": [],
  "files_count": 0,
  "dirs_count": 0,
  "size_count": 0,
  "scan_errors": []
}
```

### How To Reproduce

codebase to scan: https://mirrors.bfsu.edu.cn/apache/mina/ftpserver/1.1.1/apache-ftpserver-1.1.1-src.tar.bz2
commands: `scancode --license --info --only-findings --license-text --strip-root --license-score 80 --json-pp <output.json> <path_to_codebase>`

### System configuration

* What OS are you running on? (Linux)
* What version of scancode-toolkit was used to generate the scan file? (21.8.4)
* What installation method was used to install/run scancode? (pip)

**Comment by pombredanne** [comment]
Thank you for the report: I think the things are correct as they are though!

The short answer is that:

- ScanCode `x11` is mapped to SPDX `ICU`
- ScanCode `x11-xconsortium` is mapped to SPDX `X11`

I reckon that may be a bit confusing. You have to understand that ScanCode history of assigning license keys goes a long way back and pre-dates SPDX and that we do not change these keys lightly especially when a license receives eventually an SPDX identifier at a later stage. Instead we just add the SPDX license id as a an attribute when one is assigned.

Here the scancode license key `x11` (lowercase) at https://scancode-licensedb.aboutcode.org/x11.html corresponds to the SPDX license key `ICU` (uppercase) at https://spdx.org/licenses/ICU.html . 

The back story is that SPDX assigned an `ICU` id to this license ( https://spdx.org/licenses/ICU.html ) based on Fedora's license wiki naming this license the "MIT Modern style (ICU Variant)" at https://fedoraproject.org/wiki/Licensing:MIT#Modern_style_.28ICU_Variant.29 becasue of its use in the `ICU` project and library.

Yet even though the IBM copyright in ICU code files using this license dates back to 1995, back then IBM used first the IBM PUBLIC LICENSE 1.0 for these ICU libraries and not what SPDX calls the `ICU` license today. ICU (the library) adopted what's dubbed the SPDX `ICU` license with version 1.8.1 and later only in June 2001.

In contrast we assigned this license with the scancode `x11` (at https://scancode-licensedb.aboutcode.org/x11.html) key because it has been seen first used by the X11 project. This is something that pre-dates ICU using of the license text by several years.

You can see it in use in X11 at https://www.xfree86.org/4.0.1/LICENSE3.html#7

And what SPDX calls `X11` (uppercase) at https://spdx.org/licenses/X11.html is what we at scancode named the `x11-xconsortium` at https://scancode-licensedb.aboutcode.org/x11-xconsortium.htmlas it first show up in https://www.xfree86.org/3.3.6/COPYRIGHT2.html#3 under an X-Consortium heading.

I am tempted to say that our id are better based on history, but that's really a minor point. We co-founded SPDX and it is hugely popular now!

We could deprecate our own scancode `x11` and use an SPDX-like `icu`. But then we could not really reassign ever the `x11-xconsortium` key we use to be the `x11` key since it is or was already in use for is SPDX calls `ICU`.

Any of this may create quite a bit of churn for our users so I am not really inclined to do any of this.
FWIW, we are reporting both license keys in all cases as you can see below:

```
{
          "key": "x11",
.....
          "spdx_license_key": "ICU",
          "spdx_url": "https://spdx.org/licenses/ICU",
          "start_line": 4,
          "end_line": 27,
          "matched_rule": {
            "identifier": "x11.LICENSE",
            "license_expression": "x11",
            "licenses": [
              "x11"
            ],
```

**Comment by pombredanne** [comment]
@yunhua-deng I hope the comments I make sense for you. I am closing this for now. Feel to reopen if this was not clear or if you have further questions. Thank you for using ScanCode!

**Comment by yunhua-deng** [comment]
Thank you for the detailed elaboration. This case is complicated but understandable.
