### ISSUE TITLE
Add matched rule to the license scan results

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#286]
This is an important an easy addition for tracing and debugging,

**Comment by balusarakesh** [comment]
I think it would be a good idea to show the matched license text too, but only in the `html-app`. I mean a small feature should be added which will show the matched license text in a new column. Sometimes the license text could be too long and may disturb the html view with its size. So, in order to avoid this we can only show the matched license with an event like a `button click`

**Comment by pombredanne** [comment]
@rakeshbalusa Your suggestion is tracked in #304.

**Comment by pombredanne** [comment]
This has been added. Closing
