### ISSUE TITLE
Why is File.license_detections a list?

### ISSUE THREAD

**Issue by srehm** [nexB/scancode-toolkit#3297]
Hi,

I was playing aroung with v32 RC3 in order to prepare the migration of our project to the new output format version. Seems to be straight forward for the most part.
However, there is one thing I dont get:
each file contains a list of license_references. But in all my tests, all detections for a file get combined into a single entry in that list that has matches for every license in the file and finally the license_expression for that entry is made up by combining the license identifiers (e.g. gpl-3.0 AND mit).

So what is the use case for that property being a list?

Thanks in advance for the clarification.

**Comment by AyanSinhaMahapatra** [comment]
Hi @srehm, thanks for taking the time to update to scancode v32 in your project, we have lots of new license related and other updates there, that would greatly improve license detections.

On the very basic level we have license matches, and there could be many matches for a license-related-text if we don't have a exact text in our rulebase, or there are multiple license texts there (or multiple texts for the same license) that we combine into one LicenseDetection object. Now one LicenseDetection is license-related texts not more than 2-3 lines far apart, but if there are license related texts in very different parts of the file, we have different LicenseDetections for all of them, so that's why one file/resource has more than one LicenseDetections in it, and that's why `license_detections` is a list. We also divide license matches in two license detections, if there are license introductions, and other special cases also.


This has also to do with the unit of license detections going from license matches -> license detections, and how we report top level unique license detections, and references to other files for licenses, which would also get affected if we have everything in a file in one detection.

Some examples of files which have more than one LicenseDetection objects:

- [test file](https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/plugin_license/unknown_intro/scan-unknown-intro-eclipse-foundation-tycho/about_1.html) : [result file](https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/plugin_license/unknown_intro/scan-unknown-intro-eclipse-foundation-tycho.expected.json#L78)
- [test file](https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/plugin_license/unknown_intro/scan-unknown-intro-long-gaps-between/LICENSE-dist.txt) : [result file](https://github.com/nexB/scancode-toolkit/blob/develop/tests/licensedcode/data/plugin_license/unknown_intro/scan-unknown-intro-long-gaps-between.expected.json#L18)

**Comment by AyanSinhaMahapatra** [comment]
Consider this:

We have in file 1:

```
license_1 notice

code/copyrights or other things in between

reference to license_2
```

In file 2 we have:
```
license_1 notice

code/copyrights or other things in between

reference to license_2
```

Now in the present case, where LicenseDetection is the unit here, and we have multiple detections per file, there are 3 unique license detections:

1. license_1 notice
2. reference to license_2
3. reference to license_3

But if we had only one license detection per file, the unique license detections would be:
1. notice to license_1 and reference to license_2
2. notice to license_1 and reference to license_3

Which would be incorrect, so we don't do that.

**Comment by srehm** [comment]
Thanks, that makes sense. :)
Closing the issue.
