### ISSUE TITLE
Add new blender license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3308]
This license should be tracked https://projects.blender.org/blender/blender/src/branch/main/release/text/copyright.txt
This is essentially a wrapper around the GPL, not sure if this is an exception of sorts?
@AyanSinhaMahapatra @DennisClark @lechasseur ping... what do you make of this fine license?

**Comment by LeChasseur** [comment]
Is this a coincidence or who told you about this licence? I'm in contact with the Stichting Blender Foundation to clarify the background.

**Comment by pombredanne** [comment]
> Is this a coincidence or who told you about this licence? I'm in contact with the Stichting Blender Foundation to clarify the background.

@LeChasseur ... @armijnhemel  mentioned to me that this was missing in ScanCode... and this is definitely an odd license (to me)

**Comment by DennisClark** [comment]
Odd indeed. The blender "license" refers to "the GNU GPL" which turns out to be gpl-2.0 if you read the COPYING file of the blender project:
https://projects.blender.org/blender/blender/src/branch/main/COPYING
because it points to this:
https://projects.blender.org/blender/blender/src/branch/main/release/license/GPL-license.txt
which is a copy of GNU GPL 2.0

It is difficult to determine if the blender thingy is a "license" or an "exception" but since it really does not state any exceptions but instead clarifies a few things (such as the totally free status of any art you create using the program), calling it an "exception" could be confusing and misleading, so calling it a license (even if it is a "frankenstein" license) is probably the best approach.

**Comment by DennisClark** [comment]
There is no version or year in the blender text itself, but the text of the associated COPYING file of the project has a date of 2010 in it, so I suggest that we call this license
blender-2010
and
LicenseRef-scancode-blender-2010

**Comment by LeChasseur** [comment]
LicenseRef-scancode-blender-2010 sounds good to me.
