### ISSUE TITLE
Version 2.0.0.rc1 license info in JSON output broken?

### ISSUE THREAD

**Issue by sschuberth** [nexB/scancode-toolkit#332]
When scanning the [gli project](https://github.com/g-truc/gli), in the HTML report I get

    gli/external/glm/test/gtx/gtx_simd_vec4.cpp 	5 	25 	license 	mit

However, in the JSON report I get

      "licenses": {
        "errors": "No module named ahocorasick"
      },

I hope I'm not doing something stupid here, but this looks awkward to me.

**Comment by pombredanne** [comment]
You are not doing anything stupid and this is likely a bug. How did you install 2.0.0rc1? Using a download or a checkout? 

if you used a checkout did you just switch branches?
If you switch branches you would need to issue this command after each switch:
```
./configure --clean
```
The next run of `./scancode` will reconfigure the environment including installing the thirdparties used in that branch

**Comment by pombredanne** [comment]
Otherwise, this is likely a bug and I would need a tad more details on your OS version, python version and how you installed scancode.

**Comment by sschuberth** [comment]
I just realized issue #326 is similar. I'm using a fresh clone of scancode (`develop` branch). I'm actually running this on a CI server that does `git clean -fdx` followed by `scancode --version` (to activate scancode and show its version) each time. Then I run `scancode -f json gli/ results-gli.json`. Will report back about the OS and versions.

**Comment by sschuberth** [comment]
Ok, I think I know what was going on (spoiler: my mistake): I was not using a fresh clone as intended, but a checkout that was still at version 1.6.0. The Git working tree then got updated to version 2.0.0.rc1 but *without* running `configure` or `git clean -fdx`. Which left scancode in an awkward state resulting in the errors in the JSON output. With a real clean build I cannot reproduce the error anymore.

**Comment by pombredanne** [comment]
The key thing is to `configure --clean` to cleanup any virtualenv and configuration. 
Then run `configure` or run some `scancode` command.

The thing that happens with `configure` is that it creates a Python `virtualenv` and installs in it all the thirdparty libs that scancode uses and depends on (which are vendored in the `thirdparty` directory for sanity and network independence).

Since each branch may have a different set of thirdparty deps and/or versions, switching branches usually demands the --clean (and this is unrelated to a git clean.... all the virtualenv files are created in git ignored directories)
