### ISSUE TITLE
2.0 Installation failure

### ISSUE THREAD

**Issue by 55jr55** [nexB/scancode-toolkit#337]
Downloaded the latest 2.0 code. OS is Linux debian 3.2.0-4-486 #1 Debian 3.2.63-2+deb7u1 i686 GNU/Linux. Python version is 2.7. Installation failed with the following:
 
user@debian:~/scancode/scancode-toolkit-develop$ ./scancode --help
* Configuring ScanCode for first use...
* Activating ...
Command "/home/user/scancode/scancode-toolkit-develop/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hYZQ6B/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-AlJxVa-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/scancode/scancode-toolkit-develop/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-hYZQ6B/lxml/

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --quiet --find-links="/home/user/scancode/scancode-toolkit-develop/thirdparty/dev" --find-links="/home/user/scancode/scancode-toolkit-develop/thirdparty/base" --find-links="/home/user/scancode/scancode-toolkit-develop/thirdparty/prod" -r "/home/user/scancode/scancode-toolkit-develop/etc/conf/base.txt". Aborting...
./scancode: line 16: /home/user/scancode/scancode-toolkit-develop/bin/scancode: No such file or directory

**Comment by majurg** [comment]
Did you pull in the v2.0 changes via git? If so, try running: `./configure --clean && source configure`

**Comment by pombredanne** [comment]
Actually the issue is that the doc is not up to date and is missing important new required system packages that must be installed.

There are new XML-related prereqs are not fulfilled and in particular not yet documented in the README. Sorry for that.

You are actually missing these new packages:
`sudo apt-get install libxml2-dev libxslt1-dev` 

And the README doc should be updated to :
`On Debian/Ubuntu distros, you will need to install these packages first: libbz2 xzutils zlib1g libxml2-dev libxslt1-dev`

And the corresponding packages should be on Centos/RedHat should now be:

` On RPM-based distros, you will need to install these packages first: zlib bzip2-libs xz-libs  libxml2-devel libxslt-devel`

**Comment by pombredanne** [comment]
@55jr55 This latest update to the README should cover it. Tell if this fixes your problem.

**Comment by yahalom5776** [comment]
@pombredanne : At least on Debian 8 (Jessie) the names of two packages are different.

- xzutils -> xz-utils (https://packages.debian.org/de/jessie/xz-utils)

- libbz2 -> libbz2-1.0 (https://packages.debian.org/jessie/libbz2-1.0)

Both were already installed on my system.

**Comment by pombredanne** [comment]
@yahalom5776 Thanks! I updated the README accordingly

**Comment by 55jr55** [comment]
Install works with the new README instructions and the tip from yahalom5776. Thanks for the help!

**Comment by pombredanne** [comment]
@55jr55 great! @yahalom5776 Thanks ++

**Comment by pombredanne** [comment]
great! I am closing this.
