### ISSUE TITLE
lgpl-2.0-plus_204.RULE is incorrect

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-toolkit#3390]
The rule lgpl-2.0-plus_204.RULE is not correctly named and incorrectly points to lgpl-2.0-plus rather than lgpl-3.0-plus. 

The URL http://www.gnu.org/licenses/lgpl automatically redirects to https://www.gnu.org/licenses/lgpl-3.0 

```
---
license_expression: lgpl-2.0-plus
is_license_reference: yes
relevance: 100
ignorable_urls:
    - http://www.gnu.org/licenses/lgpl
---

http://www.gnu.org/licenses/lgpl
```

The RULE is at 
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/lgpl-2.0-plus_204.RULE

**Comment by skoehler** [comment]
Could it be that the URL `http://www.gnu.org/licenses/lgpl` used to point to lgpl-2.0 ? If the redirection of that URL changes over time, then it's a moving target and it should - probably - trigger some sort of warning!

**Comment by mjherzog** [comment]
FSF is known for using the generic lgpl and gpl URLs and then changing the target to latest license version

**Comment by pombredanne** [comment]
@DennisClark re:
> The rule lgpl-2.0-plus_204.RULE is not correctly named and incorrectly points to lgpl-2.0-plus rather than lgpl-3.0-plus.

Back then this URL was pointing to an LGPL 2.1 with some Japanese comments from ~ 2003 https://web.archive.org/web/20030415000000*/http://www.gnu.org/licenses/lgpl until early 2007 https://web.archive.org/web/20060516063307/http://www.gnu.org/licenses/lgpl

Captures from July 2007 https://web.archive.org/web/20070703205356/https://gnu.org/licenses/lgpl to October 2011 https://web.archive.org/web/20111001082314/http://www.gnu.org:80/licenses/lgpl are dead links with a 404

Then circa Feb 2012, this started to redirect to LGPL 3.0 https://web.archive.org/web/20120222063732/http://www.gnu.org:80/licenses/lgpl

Also the LGPL states that if it comes with no version per section "6. Revised Versions of the GNU Lesser General Public License.", then you can chose any version and this is likely the rationale I used for this, using the oldest lgpl version or any other version, i.e., lgpl-2.0-plus.

MO is this should be an lgpl-2.0-plus as it is OR an lgpl-2.1 if we want to update the rule, and report a relevance of 95% instead of 100.

Note that as @mjherzog stated the FSF is notoriously flaky on URLs See https://news.ycombinator.com/item?id=35831270&ref=upstract.com
And also on texts ;) https://github.com/pombredanne/gpl-history

There is also a complete history of the GNU web site redirects in this CVS!! repo https://web.cvs.savannah.gnu.org/viewvc/www/www/licenses/.symlinks?revision=1.37&view=markup

**Comment by DennisClark** [comment]
Given all the comments, let's leave the lgpl-2.0-plus_204.RULE  as it is.  Closing.
