### ISSUE TITLE
Proprietary License not detected

### ISSUE THREAD

**Issue by soimkim** [nexB/scancode-toolkit#3507]
### Description

> Please leave a brief description of the bug or feature request:
Analysis link : https://registry.npmjs.org/@vindral/web-sdk/-/web-sdk-1.1.0.tgz
README.md file : 
```
#### License and support

Vindral is a commercial product and requires an active, paid license to access and use. To obtain such a license, or in case you have any questions, do not hesitate to [get in touch](https://vindral.com/inquiries)!

Copyright RealSprint AB

```
Since it is a commercial product, the **Proprietary license** should be detected, but the license is not detected.

### How To Reproduce
1. Download the source :  https://registry.npmjs.org/@vindral/web-sdk/-/web-sdk-1.1.0.tgz
2. Run the Scancode. 
3. License is not detected for README.md file.

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? Ubuntu 20.04
* What version of scancode-toolkit was used to generate the scan file? 32.0.6
* What installation method was used to install/run scancode? pip

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra    Please create a Detection Rule that points to `proprietary-license` when this text is detected: 

`Vindral is a commercial product and requires an active, paid license to access and use.`

It is really just a notice, and not an actual license, so it does not make sense to create the text taken from the project README.md as a new license. 

Thanks in advance!

**Comment by soimkim** [comment]
@DennisClark ,
How about creating a Detection Rule that points to a `proprietary-license` for the words `commercial product` or `paid license`?

**Comment by AyanSinhaMahapatra** [comment]
Thanks @soimkim for the report, @DennisClark thanks I've added a license rule above ^ for this (excluding the company name also, if that's okay).

> How about creating a Detection Rule that points to a proprietary-license for the words `commercial product` or `paid license`?

So while adding rules which are general, we have to be mindful of false-positives, and we ask the following question:
Can this phrase be present in code without the context of a software license? which means checking if this is too general to create noise in the license detections.

`commercial product` or `paid license` is probably too general to be added IMHO (which is why they're not there currently I think), but what do you think @pombredanne @DennisClark ?

We now have a `is_license_clue` flag in license rules, which if set true, the rules would be not reflected in the detected license expressions or license detection details for a resource, but present in a seperate `license_clues` list which can be inspected for these, if required. There is an ongoing discussion on converting the more general rules into this category for now.

**Comment by DennisClark** [comment]
I agree that really short rules increase the danger of false positives and that we should avoid them.

**Comment by soimkim** [comment]
Thank you for quick response.
