### ISSUE TITLE
Convert permissive rules to license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3552]
There are two things in this licensing at https://openwall.info/wiki/people/solar/software/public-domain-source-code/md5

1. a public domain dedication: we do not need anything new for this
2. a permissive license alternative that we detected until now as "other-permissive" and would be best as its own license as it is commonly seen as code vendored in Freetype and is also used in curl md4.

I would only need 2., meaning a license for this text:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted.

There's ABSOLUTELY NO WARRANTY, express or implied.
```

There are variants with and without the trailing comment:
> (This is a heavily cut-down "BSD license".)

So we need to
- create a license
- update the detection rules to point to this new license
- possibly create new rules for the choice notices if they do not exist

**Comment by pombredanne** [comment]
Some rules impacted include these https://github.com/search?q=org%3Anexb+"There's+ABSOLUTELY+NO+WARRANTY%2C+express+or+implied."&type=code

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   Please create a new license 
key: openwall-md5-permissive
owner: Openwall
category: Permissive

text:
Redistribution and use in source and binary forms, with or without
modification, are permitted.

There's ABSOLUTELY NO WARRANTY, express or implied.

notes:
The BSD-2-Clause terms are not explicitly stated, but are strongly implied, by the license text, especially since the original notice appends this comment:  (This is a heavily cut-down "BSD license".)

url: 
https://openwall.info/wiki/people/solar/software/public-domain-source-code/md5

**Comment by AyanSinhaMahapatra** [comment]
The license was added with https://github.com/nexB/scancode-toolkit/pull/3586 and rules were re-qualified via the commit referenced above ^. Thanks @pombredanne @DennisClark closing!
