### ISSUE TITLE
'percentage_of_license_text' for 'LICENSE' file

### ISSUE THREAD

**Issue by dd-jy** [nexB/scancode-toolkit#3688]
### Description

> Please leave a brief description of the bug or feature request:
The 'percentage_of_license_text' for 'LICENSE' file  is very low. Could you explain how the 'percentage_of_license_text' is measured?
![image](https://github.com/nexB/scancode-toolkit/assets/50347670/80f97e09-1896-45f1-896d-cb5b31233b74)

### How To Reproduce

> Tell us how to reproduce the issue. 

Analyze the source code of 'https://github.com/digitalocean/prometheus-client-c (version 0.1.3 )'

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux) **Linux**
* What version of scancode-toolkit was used to generate the scan file? **32.0.2**
* What installation method was used to install/run scancode? (pip/source download/other) **pip**

**Comment by AyanSinhaMahapatra** [comment]
From the detections (attached at the end) for the LICENSE file see the following: `"start_line": 5, "end_line": 15,`

So here the first line: https://github.com/digitalocean/prometheus-client-c/blob/master/LICENSE#L1
is not detected as a license text, and hence the percentage score.

I'm not sure on whether this license should be considered as a license text, and @DennisClark would know better, we probably have to add a license detection rule for this text, so that we detect this henceforth and get a 100% on the percentage of the license text.

And this is how the license detection and this calculation of percentage of license text works:

1. The whole file is parsed and here the words are converted into tokens for matching.
2. We check these words if they are legalese words (words present already in LicenseDb license/rules and a list of special legalese words), and if we find lots of legalese words together, that part of the text is considered as a license text, and made into queries which are sent for license detection, rest are ignored.
3. We run license detection on these part(s) of texts and match these to the LicenseDb rules using a variety of methods, exact and approximate matching, and if we get matches we return the same for the file.
4. At last we check how much part of the file (how many words) we return license matches for, and how many words total the file has, and calculate the percentage from that. 

See also https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/README.rst for reference but note that this is a bit outdated and misses some additions.

```
  "files": [
    {
      "path": "LICENSE",
      "type": "file",
      "name": "LICENSE",
      "base_name": "LICENSE",
      "extension": "",
      "size": 650,
      "date": "2024-03-05",
      "sha1": "cd278efbcf9a0c332355a43d4e5efce9eaecfc5e",
      "md5": "504b00808bb24f586f95bda56539d08b",
      "sha256": "124033dc45b3d4acd66331f6bceec15b27b8145491acbbd5cb024ff338988afe",
      "mime_type": "text/plain",
      "file_type": "ASCII text",
      "programming_language": null,
      "is_binary": false,
      "is_text": true,
      "is_archive": false,
      "is_media": false,
      "is_source": false,
      "is_script": false,
      "detected_license_expression": "apache-2.0",
      "detected_license_expression_spdx": "Apache-2.0",
      "license_detections": [
        {
          "license_expression": "apache-2.0",
          "license_expression_spdx": "Apache-2.0",
          "matches": [
            {
              "license_expression": "apache-2.0",
              "spdx_license_expression": "Apache-2.0",
              "from_file": "LICENSE",
              "start_line": 5,
              "end_line": 15,
              "matcher": "2-aho",
              "score": 100.0,
              "matched_length": 85,
              "match_coverage": 100.0,
              "rule_relevance": 100,
              "rule_identifier": "apache-2.0_7.RULE",
              "rule_url": "https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/apache-2.0_7.RULE",
              "matched_text": "Licensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.",
              "matched_text_diagnostics": "Licensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License."
            }
          ],
          "detection_log": [],
          "identifier": "apache_2_0-c4e30bcd-ccfd-bbc3-d2f1-196ab911e47d"
        }
      ],
      "license_clues": [],
      "percentage_of_license_text": 80.19,
      "copyrights": [],
      "holders": [],
      "authors": [],
      "files_count": 0,
      "dirs_count": 0,
      "size_count": 0,
      "scan_errors": []
    }
```

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra  I don't think that there is necessarily anything to "fix" here, except to incorporate your detailed explanation of what the percentage score means and how it is calculated into the documentation.

**Comment by dd-jy** [comment]
Thank you for your kind explanation! I agree that there is no need to fix it.
