### ISSUE TITLE
Consider new "do not compete" license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3692]
See https://nxlog.co/nxlog-public-license via @pabs3

**Comment by DennisClark** [comment]
looks like a new license to me -- analysis in progress

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please create the following license and associated rules: 

key: nxlog-public-license-1.0
name: NXLOG Public License v1.0
short-name: NXLOG Public License v1.0
owner: NXLOG
category: Source-available
SPDX: LicenseRef-scancode-nxlog-public-license-1.0
homepage: https://nxlog.co/nxlog-public-license

Notes:
Although the license text style is copyleft, the following restrictions are not GPL-compatible: 

ii. Bundling the Software with a commercial product or using it to provide commercial services is prohibited if your product or service explicitly depends on the Software to be able to operate or function. You may use the Software without modifications to provide commercial services or to bundle it with your product provided that your service or product can also operate or function without the Software. A commercial license is available if you wish to incorporate the Software into your product or service which explicitly depends on the Software to be able to operate or function.

Text:
NXLOG PUBLIC LICENSE v1.0

1. DEFINITIONS

“License” shall mean version 1.0 of the NXLOG PUBLIC LICENSE, i.e. the terms and conditions set forth in this document;  “Software” shall mean the source code and object code form, all associated media, printed materials, and "online" or electronic documentation. All such software and materials are referred to herein as the "Software" and are copyrighted by Licensor; “Licensor” refers to the copyright holder of the Software, i.e. NXLog Ltd.

2. GRANT OF LICENSE

Licensor hereby grants you the following rights, provided that you comply with all of the restrictions set forth in this License and provided, further, that you distribute an unmodified copy of this License with the Software:

i. You may copy and distribute verbatim (i.e. unmodified) copies of the Software as you receive it, in any medium;

ii. You may modify the Software, create works based on the Software and distribute copies of such, in any medium.

By downloading, using, modifying and copying the Software (or any work based on the Software), you indicate your acceptance of this license to do so, and all its terms and conditions for using, copying, distributing and modifying the Software or works based on it. Nothing other than this license grants you permission to modify, distribute the program or its derivative works. If you do not accept these terms and conditions, do not use, modify or distribute the Software.

3. RESTRICTIONS ON COPYING, DISTRIBUTION AND USE

The Software may be copied and distributed with or without modifications in source code and object code form and may be used for commercial and non-commercial purposes provided that the following restrictions are met:

i. Distribution of the Software is prohibited if any payment is made in connection with such distribution. You may only charge a reasonable fee to cover the costs of copying and redistribution;

ii. Bundling the Software with a commercial product or using it to provide commercial services is prohibited if your product or service explicitly depends on the Software to be able to operate or function. You may use the Software without modifications to provide commercial services or to bundle it with your product provided that your service or product can also operate or function without the Software. A commercial license is available if you wish to incorporate the Software into your product or service which explicitly depends on the Software to be able to operate or function.

4. RESTRICTIONS ON MODIFICATION AND DERIVATIVE WORKS

The Software may be modified and derivative works may be distributed only under the terms of this license with the following restrictions:

i. Any modifications and enhancements to the Software, including any newly developed scripts, libraries, modules that depend on the Software, are considered derivative works (“Derivative Work”). 

ii. If you have modified the Software or created Derivative Work, you must cause the work to carry prominent notices stating that you have modified the Software's files and the date of any change. In each source file that you have modified, you must include a prominent notice that you have modified the file, including your name, your e-mail address (if any), and the date and purpose of the change;

iii. All Derivative Works must be made public in source code form by making it accessible for download over the internet. You must also notify Licensor about the Derivative Work in e-mail;

iv. All Derivative works must be distributed with an unmodified copy of this License;

v. By creating a Derivative Work, you assign all copyrights relating to the modifications to Licensor. You acknowledge that Licensor will own all copyrights and Licensor may use and distribute the Derivative Work to third parties under different terms from that of this License.

5. NO WARRANTIES

The Software is provided “AS IS” and Licensor makes no warranty as to its use, performance, or otherwise. To the maximum extent permitted by applicable law, Licensor disclaims all other representations, warranties, and conditions, express, implied, statutory, or otherwise, including, but not limited to, implied warranties or conditions of merchantability, satisfactory quality, fitness for a particular purpose, title, and non-infringement. The entire risk arising out of use or performance of the Software remains with you.

6. LIMITATION OF LIABILITY 

This limitation of liability is to the maximum extent permitted by applicable law. In no event shall Licensor be liable for any costs of substitute products or services, or for any special, incidental, indirect, or consequential damages whatsoever (including, without limitation, damages for loss of business profits, business interruption, or loss of business information) arising out of the use or inability to use the Software, even if Licensor has been advised of the possibility of such damages. In any case, Licensor's entire liability arising out of this Agreement shall be limited to the greater of the amount actually paid for the Software; provided, however, that if you have entered into a Technical Services Support Agreement, Licensor's entire liability regarding support services shall be governed by the terms of that agreement.

**Comment by AyanSinhaMahapatra** [comment]
Added, closing!
