### ISSUE TITLE
Add new ChilliCream License 1.0

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3733]
This is used in: https://www.nuget.org/packages/BananaCakePop.Middleware/
- https://www.nuget.org/packages/BananaCakePop.Middleware/15.0.4/License
- https://chillicream.com/licensing/chillicream-license
- See also https://github.com/ChilliCream/graphql-platform/issues/6704

**Comment by DennisClark** [comment]
This is an odd case.  The text at https://chillicream.com/licensing/chillicream-license states that "This is the license we use for our proprietary software like Banana Cake Pop."  but the license text itself reads pretty much like a copyleft limited. Perhaps they are simply using the word "proprietary" to indicate that it is their own software.  So I'm going with a copyleft limited interpretation.

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra   please create this new license and associated rules: 

key: chillicream-1.0
name: ChilliCream License 1.0
shortname: ChilliCream License 1.0
category: Copyleft Limited
owner: ChilliCream
spdx: LicenseRef-scancode-chillicream-1.0 
homepage URL: https://chillicream.com/licensing/chillicream-license 
other URL: https://www.nuget.org/packages/BananaCakePop.Middleware/15.0.4/License 

Text: 
ChilliCream License 1.0

Copyright License

The licensor grants you a non-exclusive, royalty-free, worldwide, non-sublicensable, non-transferable license to use, copy, distribute, make available, and prepare derivative works of the software, in each case subject to the limitations and conditions below.

Limitations

You may not move, change, disable, or circumvent the license key functionality in the software, and you may not remove or obscure any functionality in the software that is protected by the license key.

You may not alter, remove, or obscure any licensing, copyright, or other notices of the licensor in the software. Any use of the licensor’s trademarks is subject to applicable law.

Patents

The licensor grants you a license, under any patent claims the licensor can license, or becomes able to license, to make, have made, use, sell, offer for sale, import and have imported the software, in each case subject to the limitations and conditions in this license. This license does not cover any patent claims that you cause to be infringed by modifications or additions to the software. If you or your company make any written claim that the software infringes or contributes to infringement of any patent, your patent license for the software granted under these terms ends immediately. If your company makes such a claim, your patent license ends immediately for work on behalf of your company.

Notices

You must ensure that anyone who gets a copy of any part of the software from you also gets a copy of these terms.

If you modify the software, you must include in any modified copies of the software prominent notices stating that you have modified the software.

No Other Rights

These terms do not imply any licenses other than those expressly granted in these terms.

Termination

If you use the software in violation of these terms, such use is not licensed, and your licenses will automatically terminate. If the licensor provides you with a notice of your violation, and you cease all violation of this license no later than 30 days after you receive that notice, your licenses will be reinstated retroactively. However, if you violate these terms after such reinstatement, any additional violation of these terms will cause your licenses to terminate automatically and permanently.

No Liability

As far as the law allows, the software comes as is, without any warranty or condition, and the licensor will not be liable to you for any damages arising out of these terms or the use or nature of the software, under any kind of legal claim.

Definitions

The licensor is the entity offering these terms, and the software is the software the licensor makes available under these terms, including any portion of it.

you refers to the individual or entity agreeing to these terms.

your company is any legal entity, sole proprietorship, or other kind of organization that you work for, plus all organizations that have control over, are under the control of, or are under common control with that organization. control means ownership of substantially all the assets of an entity, or the power to direct its management and policies by vote, contract, or otherwise. Control can be direct or indirect.

your licenses are all the licenses granted to you for the software under these terms.

use means anything you do with the software requiring one of your licenses.

trademark means trademarks, service marks, and similar rights.

**Comment by AyanSinhaMahapatra** [comment]
Added, closing!
