### ISSUE TITLE
Add license for RHEL UBI image

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#3759]
See Red Hat Universal Base Image (English) on https://www.redhat.com/en/about/eulas#UBI
https://www.redhat.com/licenses/EULA_Red_Hat_Universal_Base_Image_English_20190422.pdf

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra  Please add the following license and associated rules:

key: rh-ubi-eula-2019
name: Red Hat Universal Base Image EULA
shortname: Red Hat UBI EULA
category: Proprietary Free
owner: Red Hat
spdx: LicenseRef-scancode-rh-ubi-eula-2019
urls: 
https://www.redhat.com/en/about/eulas#UBI
https://www.redhat.com/licenses/EULA_Red_Hat_Universal_Base_Image_English_20190422.pdf

notes: 
You agree to include this unmodified EULA in all distributions of container images sourced, built or otherwise derived from the Programs. If you modify the Red Hat Universal Base Image(s), you must remove any Red Hat trademark(s) prior to any subsequent distribution. Any breach of this Section 2 is a material breach of the EULA and you may no longer use and/or distribute the Red Hat trademark(s). Modifications to the software may corrupt the Programs.

text: 
END USER LICENSE AGREEMENT
RED HAT UNIVERSAL BASE IMAGE

This end user license agreement (“EULA”) governs the use of Red Hat Universal Base Image and associated software supporting such container(s)
and any related updates, source code, including the appearance, structure and organization (the “Programs”), regardless of the delivery mechanism.
If a Red Hat Universal Base Image is included in another Red Hat product, the EULA terms of such other Red Hat product will apply and supersede
this EULA. If a Red Hat Universal Base Image is included in a third party work, the terms of this EULA will continue to govern the Red Hat Universal
Base Image.

1. License Grant. Subject to the terms of this EULA, Red Hat, Inc. (“Red Hat”) grants to you a perpetual, worldwide license to the Programs (each
of which may include multiple software components). With the exception of the Red Hat trademark identified in Section 2 below, each software
component is governed by a license that permits you to run, copy, modify, and redistribute (subject to certain obligations in some cases) the
software components. This EULA pertains solely to the Programs and does not limit your rights under, or grant you rights that supersede, the
license terms applicable to any particular component. The license terms applicable to each software component are provided in the source code
of that component.

2. Intellectual Property Rights. The Programs and each of their components are owned by Red Hat and other licensors and are protected under
copyright law and other laws as applicable. Title to the Programs and any component shall remain with Red Hat and other licensors, subject to
the applicable license, excluding any independently developed and licensed work. The “Red Hat” trademark is a registered trademark of Red
Hat and its affiliates in the U.S. and other countries. Subject to Red Hat’s trademark usage guidelines (set forth at
http://www.redhat.com/about/corporate/trademark/), this EULA permits you to distribute the Programs that include the Red Hat trademark,
provided you do not make any statements on behalf of Red Hat, including but not limited to, stating or in any way suggesting (in any public,
private and/or confidential statement (whether written or verbal)) that Red Hat supports or endorses software built and delivered with a Red Hat
Universal Base Image(s) (such derivative works referred to as a “Red Hat Based Container Images”); provided if a Red Hat Based Container
Image is Red Hat Certified and deployed on a Red Hat supported configuration as set forth at https://access.redhat.com/articles/2726611 then
you may state that the Red Hat Universal Base Image is supported by Red Hat. You agree to include this unmodified EULA in all distributions of
container images sourced, built or otherwise derived from the Programs. If you modify the Red Hat Universal Base Image(s), you must remove
any Red Hat trademark(s) prior to any subsequent distribution. Any breach of this Section 2 is a material breach of the EULA and you may no
longer use and/or distribute the Red Hat trademark(s). Modifications to the software may corrupt the Programs.

3. Limited Warranty. Except as specifically stated in this Section 3, a separate agreement with Red Hat, or a license for a particular component,
to the maximum extent permitted under applicable law, the Programs and the components are provided and licensed “as is” without
warranty of any kind, expressed or implied, including the implied warranties of merchantability, non-infringement or fitness for a
particular purpose. Neither Red Hat nor its affiliates warrant that the functions contained in the Programs will meet your requirements or that
the operation of the Programs will be entirely error free, appear or perform precisely as described in the accompanying documentation, or comply
with regulatory requirements. Red Hat warrants that the media on which the Programs and the components are provided will be free from defects
in materials and manufacture under normal use for a period of 30 days from the date of delivery to you. This warranty extends only to the party
that purchases subscription services for the supported configurations from Red Hat and/or its affiliates or a Red Hat authorized
distributor.

4. Limitation of Remedies and Liability. To the maximum extent permitted by applicable law, your exclusive remedy under this EULA is to return
any defective media within 30 days of delivery along with a copy of your payment receipt and Red Hat, at its option, will replace it or refund the
money you paid for the media. To the maximum extent permitted under applicable law, under no circumstances will Red Hat, its affiliates,
any Red Hat authorized distributor, or the licensor of any component provided to you under this EULA be liable to you for any incidental
or consequential damages, including lost profits or lost savings arising out of the use or inability to use the Programs or any
component, even if Red Hat, its affiliates, an authorized distributor, and/or licensor has been advised of the possibility of such
damages. In no event shall Red Hat's or its affiliates’ liability, an authorized distributor’s liability or the liability of the licensor of a
component provided to you under this EULA exceed the amount that you paid to Red Hat for the media under this EULA.

5. Export Control. As required by the laws of the United States and other countries, you represent and warrant that you: (a) understand that the
Programs and their components may be subject to export controls under the U.S. Commerce Department’s Export Administration Regulations
(“EAR”); (b) are not located in a prohibited destination country under the EAR or U.S. sanctions regulations (currently Cuba, Iran, North Korea,
Sudan, Syria, and the Crimea Region of Ukraine, subject to change as posted by the United States government); (c) will not export, re-export, or
transfer the Programs to any prohibited destination, persons or entities on the U.S. Bureau of Industry and Security Denied Parties List or Entity
List, or the U.S. Office of Foreign Assets Control list of Specially Designated Nationals and Blocked Persons, or any similar lists maintained by
other countries, without the necessary export license(s) or authorizations(s); (d) will not use or transfer the Programs for use in connection with
any nuclear, chemical or biological weapons, missile technology, or military end-uses where prohibited by an applicable arms embargo, unless
authorized by the relevant government agency by regulation or specific license; (e) understand and agree that if you are in the United States and
export or transfer the Programs to eligible end users, you will, to the extent required by EAR Section 740.17(e), submit semi-annual reports to
the Commerce Department’s Bureau of Industry and Security, which include the name and address (including country) of each transferee; and
(f) understand that countries including the United States may restrict the import, use, or export of encryption products (which may include the
Programs and the components) and agree that you shall be solely responsible for compliance with any such import, use, or export restrictions.

6. Third Party Software. The Program may be provided with third party software programs subject to their own license terms. The license terms
either accompany the third party software programs or, in some instances, may be viewed at www.registry.redhat.com. If you do not agree to
abide by the applicable license terms for the third party software programs, then you may not install, distribute or use them.

7. General. If any provision of this EULA is held to be unenforceable, the enforceability of the remaining provisions shall not be affected. Any claim,
controversy or dispute arising under or relating to this EULA shall be governed by the laws of the State of New York and of the United States,
without regard to any conflict of laws provisions. The rights and obligations of the parties to this EULA shall not be governed by the United
Nations Convention on the International Sale of Goods.

Copyright 2019 Red Hat, Inc. All rights reserved. “Red Hat,” is a registered trademark of Red Hat, Inc. All other trademarks are the property of their respective owners.

**Comment by AyanSinhaMahapatra** [comment]
Added this, closing!
