### ISSUE TITLE
Missing license: Redpanda Community License Agreement

### ISSUE THREAD

**Issue by armijnhemel** [nexB/scancode-toolkit#3791]
https://github.com/redpanda-data/redpanda/blob/dev/licenses/rcl.md

**Comment by DennisClark** [comment]
@AyanSinhaMahapatra  Please synch with the following new DejaCode license: 

https://enterprise.dejacode.com/licenses/nexB/redpanda-community-la/ 

It is actually a composite license, with the primary one being Source-available.

**Comment by armijnhemel** [comment]
Some background information for those who are interested: https://www.warpstream.com/blog/announcing-bento-the-open-source-fork-of-the-project-formerly-known-as-benthos

**Comment by pombredanne** [comment]
@armijnhemel Thanks!

FWIW, we keep the DejaCode and SacnCode licenses in sync using this script:https://github.com/nexB/scancode-toolkit/blob/develop/etc/scripts/licenses/synclic.py

Here Dennis started by creating the license in DejaCode and asked Ayan to sync up ScanCode with DejaCode. Sometimes we do it the other way :) But this is a new license in all cases, otherwise Dennis would have pointed you to the existing license.

**Comment by AyanSinhaMahapatra** [comment]
Added, closing this.
