### ISSUE TITLE
Add new tests (and possibly licenses and rules) from https://github.com/retrography/OS-Licenses/

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#54]
Some licenses in https://github.com/retrography/OS-Licenses/ by @retrography may not be detected as full exact licenses. They should

**Comment by retrography** [comment]
Hi @pombredanne! Do you mean that they are not included in scancode-toolkit or that the license texts I have are not accurate? I am asking because my list is by no means complete. I just gathered a bunch of them that I needed for a research projects. There are much more comprehensive collections at the following repos:

https://github.com/idleberg/Creative-Commons-Markdown by @idleberg
https://github.com/okfn/licenses by @okfn
https://github.com/ufal/lindat-license-selector by @ufal
https://github.com/oss-collections/licenses by @oss-collections

**Comment by pombredanne** [comment]
@retrography Thanks! Your pointers are valuable.

The licenses in scancode (all the 1000+ of them) are in plain vanilla text too in https://github.com/nexB/scancode-toolkit/tree/master/src/licensedcode/data/licenses
The dataset is CC-0 public domain too like yours. 

I would be glad to submit a PR if you want, though your value may be diluted a bit if you get a ~1000 new licenses? 

On the scancode side, and about your dataset, I found out after a quick scan that there is an opportunity for some refinements to ensure the license detection rules are more comprehensive or the need to add some not yet covered (less common) licenses that are in your list and not yet in scancode such as the hilarious https://github.com/adversary-org/wtfnmf/blob/master/COPYING.WTFNMFPL
or the more serious but less common CECIL-2.1 

Generally speaking I am always on the lookout for new bits to enhance the license detection dataset.

**Comment by retrography** [comment]
@pombredanne Oh, I hadn't noticed the content of this directory. That is a great collection, I actually won't need to put these licenses together anymore. 

Don't worry about my collection, it can stay as it is. But I think it will be great if you can separate the license collection from the main repository and put it in a separate repository, and then link the two repos. Like that your license collection gains more visibility on its own, and it can be used as a reference for other possible projects (like text analysis of the OS licenses, etc...). And also, people will tend to contribute new licenses to your collection, if the collection becomes the reference on the matter.

By the way, this is a great piece of software. I am looking forward to using it for the next version of my paper. The README file of the project needs a "How to cite" section, so that the users get to know how they can cite your work.

**Comment by pombredanne** [comment]
@retrography
> But it'd be great if you can separate the license collection from the main repository and put it in a dedicated repository, and then link the two repos.

A great idea indeed.... I hate using git submodules though that can be easily fixed with a quick script, and to you point it makes the collection actually visible and not buried down with the code. It is carefully and continuously curated with several additions very week!
 
> By the way, this is a great piece of software. I am looking forward to using it for the next version of my paper. The README file of the project needs a "How to cite" section, so that the users get to know how they can cite your work.

Thanks for the kudos!
About "how to cite", the generated scans contain a small disclaimer which should be all you need (see https://github.com/nexB/scancode-toolkit/blob/master/NOTICE#L20 ) but I am less familiar with citations, what would be your take on how to present a real citation?

**Comment by retrography** [comment]
@pombredanne 

We can't include that kind of disclaimer in an academic paper. An academic citation follows a very specific format. I give you an example from the `statnet` package that I use regularly for my analysis:

> Handcock M, Hunter D, Butts C, Goodreau S, Krivitsky P, Bender-deMoll S and Morris M (2015). _statnet: Software Tools for the Statistical Analysis of Network Data_. [The Statnet Project](http://www.statnet.org). 

You can also provide the bibliographic entry, so that the users can format the citation according to the outlet they publish in:

```
@Misc{,
  author = {Mark S. Handcock and David R. Hunter and Carter T. Butts and Steven M. Goodreau and Pavel N. Krivitsky and Skye Bender-deMoll and Martina Morris},
  title = {statnet: Software Tools for the Statistical Analysis of Network Data},
  organization = {The Statnet Project (\url{http://www.statnet.org})},
  year = {2015},
  note = {R package version 2015.6.2},
  url = {CRAN.R-project.org/package=statnet},
}
```

**Comment by pombredanne** [comment]
thanks mucho... @retrography should their be person names or an org name is enough (or not OK?) ?

**Comment by pombredanne** [comment]
stupid question... sorry: your example is clear

**Comment by retrography** [comment]
@pombredanne No, it is not silly.

The most important field is the author field. That is the field that necessarily appears and is emphasized in every citation format. The organization field may be ignored/suppressed in some. So, make sure you set the author field to what you want to be known as the actual author of the software. This may be a person, or a collective, but actual individuals are preferred. 

When you put your organization as author, it will appear in the citation as follows:

> Centers for Disease Control and Prevention. (2009). CDC recommendations for the amount of time persons with influenza-like illness should be away from others. Retrieved from http://www.cdc.gov/h1n1flu/guidance/exclusion.htm

**Comment by pombredanne** [comment]
Fixed in develop
