### ISSUE TITLE
Makefile.am in glade 3.14.0 detected as GPL|LGPL|CPL 1.0 

### ISSUE THREAD

**Issue by richardfontana** [nexB/scancode-toolkit#550]
ScanCode detects GPL, LGPL and CPL 1.0 in the Makefile.am file in glade 3.14.0
https://git.gnome.org/browse/glade/tree/Makefile.am?h=glade-3-14

I am not sure the detection of GPL and LGPL should be considered "wrong" (from a scanning point of view rather than a legal point of view) given that the file contains the strings
	COPYING.GPL \
	COPYING.LGPL \

But it seems the only reason CPL 1.0 is detected is some rule that must be based on some real-world case of GPL|LGPL|CPL triple-licensing is matched? (I am guessing).

[Makefile.am-scancode.txt](https://github.com/nexB/scancode-toolkit/files/832307/Makefile.am-scancode.txt)

**Comment by pombredanne** [comment]
@richardfontana thanks. I can fix in two different ways:

1. make this sequence `COPYING.GPL COPYING.LGPL`  a false positive because this is what this is when this is all that is matched

2. bump the minimum required coverage of the matched rule https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/cpl-1.0_and_gpl_and_lgpl.RULE that was matched here: it should require more words to be matched to be truly relevant.

Here the `"match_coverage": 5.19` is low e.g only 5.19% of the original rule works were matched.
I guess I will do both in this special case.

**Comment by pombredanne** [comment]
@richardfontana This partially fixed in develop. Partially because I did not hide the detection of a bare GPL and a bare LGPL in this case. I can. What do you think?

**Comment by richardfontana** [comment]
@pombredanne probably useful to have the partial detection, I think.

**Comment by pombredanne** [comment]
@richardfontana we think alike. 

Vaguely related: Please ping me when there are new releases of https://github.com/copyleft-next/copyleft-next so that I can make sure the new versions are added to the detectable licenses right away.

Thanks and closing
