### ISSUE TITLE
extractcode tries to extract shell scripts

### ISSUE THREAD

**Issue by majurg** [nexB/scancode-toolkit#551]
When using `extractcode` on typical archive files, I get error text on the output of the extraction, as seen in the attached picture: 

![screen shot 2017-03-09 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/7485204/23776678/93575232-04e4-11e7-8a5d-10cfe64298f8.png)

The archive itself gets extracted fine, it just seems like `extractcode` attempts to extract shell scripts. This same behavior is experienced on a multitude of different archives.

**Comment by pombredanne** [comment]
@majurg Thanks. Yes it does.... because these could be SHAR, e.g. shell archives... but since these are not super common, no error should be issued when an extraction attempts fails in that case.

**Comment by kartiksibal** [comment]
@pombredanne Can this be resolved by adding an exception, for SHAR files, in `extrac_cli.py`  _extract_end()_ method?

**Comment by pombredanne** [comment]
@kartiksibal that may work: But I would likely rather look on the side on the archive extraction functions rather than the extract_cli
do you care for a patch?

**Comment by kartiksibal** [comment]
@pombredanne I looked into `archive.py` prior to `extrac_cli`, I had thought of editing the `SHAR` handler to incorporate, these. I somehow didn't find this approach efficient enough. I'll look for an alternate approach. 

PS: It'd be lovely if you could provide your input on #513, whenever you can allocate time. :-)

**Comment by yasharmaster** [comment]
@kartiksibal if you're not working on this, can I give it a try? @pombredanne

**Comment by kartiksibal** [comment]
@yasharmaster I am on it. I was waiting for @pombredanne input.

**Comment by kartiksibal** [comment]
@yasharmaster But, I think it'd be better if you discuss your approach towards this issue, with @pombredanne, since if you have a more efficient approach. Please go ahead with it. :-)

**Comment by pombredanne** [comment]
FWIW, having a SHAR handler than does not error out when trying to extract a non-SHAR shell script is the way I would consider the best.

**Comment by kartiksibal** [comment]
@pombredanne I'll get onto it then.

**Comment by kartiksibal** [comment]
@pombredanne While I was testing my code, I came across a weird behaviour. 

Note: For testing i have used the same file as @majurg did.

On Ubuntu 16.10, if I was to, without any altercations run `extractcode filename`, on the dev version of scancode, I get-

![screenshot from 2017-03-15 20-56-03](https://cloud.githubusercontent.com/assets/10362901/23956890/dff888d4-09c3-11e7-9e83-484766d9830f.png)

_It gives out error just for `apidocs.sh`_

On Ubuntu 16.10, but with the stable version of scancode. It works fine.

![screenshot from 2017-03-15 21-15-17](https://cloud.githubusercontent.com/assets/10362901/23957207/d90103de-09c4-11e7-926d-bf602743956e.png)
 
On MacOsSierra, Ver 10.12, I can replicate the bug, to a certain extent. 

![screen shot 2017-03-15 at 9 05 19 pm](https://cloud.githubusercontent.com/assets/10362901/23956977/2d0d4d30-09c4-11e7-9c53-1c4af9ee2b95.png)

I have tried debugging the flow of control on all the platforms, across both the stable and dev version. But, I was unable to justify the behaviour. Could you please throw some light on this?

**Comment by pombredanne** [comment]
@kartiksibal good catch. I pushed some changes to extraction yesterday. These could be the reason.
OR I noticed that the file type returned on Mac is sometimes a tad different per #438 and this could lead possibly to a different behavior on Mac. For now, I think the right way is to ensure that you get tests that pass on all OSes even if this means having a different test expectation on each OS... Having the code that handles the shell extraction deal with things in an os-neutral way is the likely better solution.

**Comment by pombredanne** [comment]
The key to trace how things behave could be to enable debug tracing by seting these flags to True locally (do not commit that) in these places:
- https://github.com/nexB/scancode-toolkit/blob/21b6c8456f6cfd42ffc07411312cc489adec26d5/src/extractcode/extract.py#L40
- https://github.com/nexB/scancode-toolkit/blob/21b6c8456f6cfd42ffc07411312cc489adec26d5/src/extractcode/archive.py#L53

And you can decide which one gives you the proper logging details.
In you case, my hunch is the "voting and scoring" of extraction handlers that would help you understand why there is a variable behavior on each OS.

**Comment by kartiksibal** [comment]
@pombredanne I had used `debug trace`, prior. But, shifted to `pdb` instead, because of the added functionalities.

I was actually focusing more on `pick best handler`, since the results of `score` are sort of put into action here. I have almost traced, all the methods in `archive.py` & `extract.py`, after which. I gave up and shot up this reply. :sweat_smile: 

I must have surely missed something. I'll dig deeper. :-)

**Comment by pombredanne** [comment]
I am old school. I do not use debuggers but tracing. Try turning on the TRACE flags I listed above.

**Comment by kartiksibal** [comment]
@pombredanne First of all apology for the delay. The reason why the file won't error out in the stable version is because of the presence of 

![untitled](https://cloud.githubusercontent.com/assets/10362901/24260769/eceb553c-101a-11e7-9188-a5f31fd3e8f0.png)

Since, the mime type matches. What I had originally thought of was to edit how the scoring was done. It should not increase the score if the mime type matches but the _extension_ doesn't. It would work in this case, since the extension is `.jar` and I think it should in a broad sense. 

But, is this approach efficient in a general sense? Is what I am a little unsure about. Please share your thoughts.

**Comment by pombredanne** [comment]
shar support is not enabled because we do not have a shar extractor that can run consistently on most shars and on Windows, Linux and Mac. It would need to be parsing the shell and finding when the payload starts and then try regular extractor/decompressor from there. shars (are/were) uncommon enough that it has not been an issue until now. 
As you found out, the reason why shell files are extracted (and failing) is because of the addition of spring boot support (these are zips with a shell prefix making them self executable Java apps. This is not a super common format and it tries eventually to extract any shell script as a zip.

**Comment by pombredanne** [comment]
I pushed a branch with a possible fix (though I did not even run it nor checked the tests): the approach is to have an extractor wrapper that does not fail with errors at all, and use it only for Springboot shell-zips.

**Comment by kartiksibal** [comment]
@pombredanne Was working exactly on that. Your fix works fine. I was looking forward to close this. :cry:

**Comment by pombredanne** [comment]
Please go ahead to finish it and make it yours.

**Comment by kartiksibal** [comment]
@pombredanne Sir, you have already done everything. What else needs doing for this?

**Comment by pombredanne** [comment]
@kartiksibal as I said "(though I did not even run it nor checked the tests)" ... so my possible fix has not been tested and has no unit tests. You can go ahead and add these :)

**Comment by kartiksibal** [comment]
@pombredanne Yeah I realised that a little later. 😅 
I'll add the tests. :-)

**Comment by pombredanne** [comment]
thx!

**Comment by pombredanne** [comment]
Fixed in develop, with tests.
@majurg @kartiksibal Thanks!
