### ISSUE TITLE
Add coverage and coding standard checks to CI runs

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#564]
In order to ease the review of PRs, we should add new checks for code coverage and coding standard.
DRF does a decent job there as pointed to me by @tdruez : https://github.com/tomchristie/django-rest-framework/blob/master/runtests.py

**Comment by pombredanne** [comment]
I wonder if we can also have checks for the format of the commit messages too. I am sure this exists somewhere.

**Comment by yasharmaster** [comment]
@pombredanne 
I would like to work on this. How should I get started?

**Comment by michaelrup** [comment]
Here are a few links, which I think are interesting to look at:
- code coverage: [codecov](https://codecov.io/) or [coveralls](https://coveralls.io/) 
- coding standard: [flake8](http://flake8.pycqa.org/en/latest/) and [isort](https://pypi.python.org/pypi/isort) as seen in [DRF](https://github.com/tomchristie/django-rest-framework/blob/master/runtests.py) 
- commit messages: [gommit](https://github.com/antham/gommit) looks interesting

**Comment by singh1114** [comment]
@pombredanne For the commit messages, can we use something like this:

https://github.com/commitizen/cz-cli
I think the repo is MIT licensed.

**Comment by all3fox** [comment]
About code coverage:

Since `scancode-toolkit` already runs on travis-ci (has a `.travis.yml`) and runs unittests with pytest, then theoretically code coverage should not be hard:

1. Enable travis for the repository (already done)
2. Enable `coveralls.io` (say) for the repository
3. Install `pytest-cov`, `pytest-xdist` and `coveralls` in `.travis.yml`
4. Add an `after-success` wich will send collected stats with `coveralls` to `coveralls.io` 

So, something like this (simplifying, `.travis.yml` for scancode-toolkit is more complicated and has a matrix):

```
install:
  - pip install pytest pytest-cov pytest-xdist coveralls
script:
  - pytest --cov=src tests
after_success:
  - coveralls
```

Applying this approach did not quite work for me, see [my branch][1] and [resulting travis builds][2] (failing).

1. Tried `pip install` just after configure:

```
install:
  - ./configure
  - pip install pytest-cov pytest-xdist coveralls
```

That failed as [first series of builds][3]

2. Fiddled with `--cov-append` and ignoring/including directories, not really the problem right now. Second [series of builds][2]

3. Tried to install `pytest-cov` from within `./configure`, modified `etc/conf/dev/base.txt` for that to look like this:

```
# Testing
apipkg
py
pytest
pytest-cov
pytest-xdist
colorama
coveralls
execnet
bumpversion
```

That resulted in a [third series of failed builds][5]. That also breaks local install on my machine (coveralls is not shipped with ScanCode)

At this point I realised that `scancode-toolkit` aggressively avoids downloading packages and uses some in-house system to keep track of dependencies. Well, my time to go get some sleep then.

[1]: https://github.com/all3fox/scancode-toolkit/blob/b2b884d91565ff3972b4342c5f3bcf98bc40f036/.travis.yml
[2]: https://travis-ci.org/all3fox/scancode-toolkit/branches
[3]: https://travis-ci.org/all3fox/scancode-toolkit/builds/215347195
[5]: https://travis-ci.org/all3fox/scancode-toolkit/builds/215351223

**Comment by all3fox** [comment]
About commit messages:

There are *very* many projects, which is why I would strongly suggest sticking to Python-based ones (so as not to introduce extra infrastructure like `npm` if you go with a javascript test tool or whatever Go uses).

There is, for instance, a Python-based **co**de **an**alyzer called [coala][1] which does all sorts of static analysis for many languages (by wrapping other tools like `flake8` etc or shipping their own). They also have a module that checks commits that even goes as far as use `nltk` to hunt down that imperative case: https://github.com/coala/coala-bears/issues/243

Full disclosure: I am involved with coala. 

[1]: https://github.com/coala/coala-bears#languages-supported

**Comment by pombredanne** [comment]
@all3fox this looks awesome. Thanks for going through all this!

Some comments that explain your woes

We have this peculiar way to bundle all the deps with `configure` and `etc/configure.py` scripts. `py.test` and `xdist` are already included. Adding `coveralls` and `pycov` (and all theirs deps) should land in https://github.com/nexB/scancode-toolkit/tree/develop/thirdparty/dev and the corresponding requirements would go in https://github.com/nexB/scancode-toolkit/blob/develop/etc/conf/dev/base.txt
So if this is bundled (and this is a minor point that can be done once you have a working config), we would bundle the deps and `./configure` would take care of their install in dev and the CIs.

Now you may wonder why we do this weird stuff? This is a way to control very strictly the deps we use and ensure reproducible runs at all times. And this is a way to ensure that a simple checkout or download is self-contained which has several benefits wrt. development and installation (e.g. no network access needed). 

This is also outlined here: https://github.com/nexB/scancode-toolkit/wiki/Development and the inner workings of the `etc/configure.py` should be documented in the code itself. ( as a side note this does not preclude ScanCode to be used as a lib and this will eventually be dealt with #24 )

**Comment by pombredanne** [comment]
@all3fox re Coala. I have tracked this for a while and this looks great. That is likely what the doctor ordered with a pinch of pylint and flake8. Your recommendation is welcomed.

**Comment by pombredanne** [comment]
@all3fox feel free to submit a PR even if this WIP, this will be easier for the discussion and you seem to have been there a bit per http://all3fox.github.io/2016/08/16/gsoc16-at-commitplease.html :)

**Comment by pombredanne** [comment]
@michaelrup thanks! these links look great.

**Comment by pombredanne** [comment]
@singh1114 https://github.com/commitizen/cz-cli seems to be more client-side and a developer tool.  We are looking for something on the CI/test suite side instead. The two can go hand in hand of course.

**Comment by pombredanne** [comment]
@all3fox I enabled `coveralls.io` on the repo.

**Comment by all3fox** [comment]
TIL: add a "Refs: link" section to your commit message only at the very end when writing a final/good commit message. Otherwise, your attempts spam the issue.

On a more serious note (not really): the "easy" label is classic [planning fallacy][1] 😺 

[1]: http://www.hpmor.com/chapter/6

**Comment by all3fox** [comment]
Coverage reports with coveralls have recently landed in `develop`. See [README.rst][1] for the badges.

However, the libraries that are used for this (namely, `pytest-cov` and `coveralls`) are being `pip install`ed in `.travis.yml` and do not currently come directly with `scancode-toolkit`. Adding these libraries into `thirdparty/` and `etc/conf` is probably a logical next step.

The catch is a dependency library, [`coverage`][2], has C extensions and cannot be built as a universal wheel (like the `py2.py3-any-none` wheels that are currently in `thirdparty/`). @pombredanne repeatedly ([here][3] and [here][4]) tells me that you could use a CI service to build the wheel and then upload it to [bintray][5]. That part I understand.

Do I then just manually download (all of the wheels versions for different platforms) and put those wheels into the `scancode-toolkit` repo then? Or is there some part of `./configure` that actually attempts to use bintray if it does not find a local wheel?

So, the goal now is to get rid of `pip install` lines in `.travis.yml`

[1]: https://github.com/nexB/scancode-toolkit#build-and-tests-status
[2]: https://pypi.python.org/pypi/coverage/4.3.4
[3]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-289630703
[4]: https://github.com/nexB/scancode-toolkit/pull/577#issuecomment-290208495
[5]: ttp://dl.bintray.com/pombreda/thirdparty/

**Comment by majurg** [comment]
@all3fox normally you would manually download the wheels for all the different platforms, if they exist. 

@pombredanne correct me if I am wrong

**Comment by pombredanne** [comment]
@majurg yes. And/or build them, then wee bundle them

**Comment by pombredanne** [comment]
this is fixed and merged in develop. Thank you all... Closing!
