### ISSUE TITLE
json2csv - memory error when input is huge [need to support Wind64]

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#616]
```
Traceback (most recent call last):
  File "json2csv.py", line 256, in <module>
    cli()
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\CYL\git\scancode-toolkit\lib\site-packages\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "json2csv.py", line 252, in cli
    json_scan_to_csv(json_input, csv_output)
  File "json2csv.py", line 80, in json_scan_to_csv
    rows = list(flatten_scan(scan_results, headers))
  File "json2csv.py", line 132, in flatten_scan
    lic = OrderedDict()
MemoryError
```

I get the above `MemoryError` when dealing with a 127MB input JSON file.
However, @JonoYang ran the same input with no problem.

**Comment by majurg** [comment]
@chinyeungli How much RAM does your machine have?

**Comment by chinyeungli** [comment]
16GB

**Comment by JonoYang** [comment]
The version of Python shipped with ScanCode that is used by Windows is 32-bit, whereas the version of Python shipped with ScanCode that is used by Linux is 64-bit. I used the test from [here](https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os) to determine if a 32-bit or 64-bit version of Python is being used. I'm guessing that the MemoryError is due to the 32-bit version of Python not being able to use as much memory as the 64-bit version of Python.

In this case, I would suggest running `json2csv.py` in a POSIX environment as there is not much we can do to reduce memory usage when dealing with such a large scan file.

**Comment by pombredanne** [comment]
@JonoYang I think this can be improved with streaming and should not be closed.

**Comment by JonoYang** [comment]
@pombredanne Is there any particular reason why the 32-bit version of Python is used for ScanCode on Windows?

**Comment by pombredanne** [comment]
@JonoYang the only reason is that we did not port and test all the libraries that are native to Win64.

**Comment by sschuberth** [comment]
I'm now seeing a very similar error when scanning a 94 MiB JSON file with ScanCode version 2.2.1.post277.4d68f9377, on both Linux and Windows. I'm wondering whether ScanCode is still trying to interpret the JSON instead of handling it as a BLOB despite my *not* specifying the `--package` option, and whether that's causing the huge memory usage.

My full command line is

    scancode --copyright --license --license-text --info --only-findings --strip-root --timeout 300 --processes 15 /dir/to/scan --json-pp result.json

**Comment by pombredanne** [comment]
@sschuberth ScanCode is unlikely to try to interpret it and this is likely the root of the issue.
JSON should not be treated as plain data when this is compact, single line.
Is this file a single line, like a huge js.map map file?

I am working on sorting out this kind of issues with both js.map map files and minified JS.

Note this is not a json2csv issue, but should be a new issue IMHO.

**Comment by sschuberth** [comment]
> Note this is not a json2csv issue, but should be a new issue IMHO.

Agreed: https://github.com/nexB/scancode-toolkit/issues/958.

**Comment by JonoYang** [comment]
@chinyeungli No update on this issue as of yet

**Comment by pombredanne** [comment]
@chinyeungli this should be working now... but slightly differently:
Try this using the latest develop:

`scancode --from-json <path to existing JSON scan> --csv <path to CSV>`

**Comment by pombredanne** [comment]
I think this is a 32bits Python limitation on Windows. let me see if we can get the Win64 version working: this would likely fix this

**Comment by pombredanne** [comment]
this no longer applies as json2csv is legacy as well as win32 (we now only support win64), therefore I am closing. We should have no issues with large JSON and CSV on windows now, assuming there is enough RAM.
