### ISSUE TITLE
Failed to Scan properly: maven project

### ISSUE THREAD

**Issue by kalagp** [nexB/scancode-toolkit#658]
We are getting the following message while scanning a maven project. And, we are not getting this error if we use the 1.6 version . (https://github.com/nexB/scancode-toolkit/releases/tag/v1.6.0)

Attached the log file
[nexB.txt](https://github.com/nexB/scancode-toolkit/files/1103652/nexB.txt)

**Comment by pombredanne** [comment]
@kalagp Thank you. This mean that these maven poms are not handled properly. For now you can either ignore this (or explicitly avoid package scan) ...
Ignoring is fine and in this case you will just not get proper details for these POMs.
I will fix it asap otherwise. Now something that would help a lot is to get some details on the POMs. I reckon these may be a private file  though it will be  a tad harder to fix the bug without haing access to the file.
If that's possible you can send this POM privately to me at pombredanne@nexb.com and I will keep this is private and it will help track me the bug.

**Comment by kalagp** [comment]
@pombredanne sent a private email

**Comment by pombredanne** [comment]
@kalagp This should be fixed in develop! Thanks ++ for this report. Can you give it a shot with the develop branch?

**Comment by pombredanne** [comment]
@kalagp Fixed and released in 2.0.1. Thanks for using ScanCode!

**Comment by kalagp** [comment]
Perfect!! its working in 2.0.1
