### ISSUE TITLE
Add RH trademark notice as detectable license

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#676]
```
# Any Red Hat trademarks that are incorporated in the source
# code or documentation are not subject to the GNU General Public
# License and may only be used or replicated with the express permission
# of Red Hat, Inc.
```
Though this may be obvious this might deserve explicit detection

**Comment by pombredanne** [comment]
There is already a license entry for https://github.com/nexB/scancode-toolkit/blob/f1f6e2cc29516455ac1732787658ede2b927f8d0/src/licensedcode/data/licenses/red-hat-trademarks.LICENSE .... 

I guess this new text could be a new entry with a key such as `red-hat-trademarks-notice`
@richardfontana what's you take on this?

**Comment by richardfontana** [comment]
@pombredanne I am perhaps biased here but I think the value of detecting that notice is low. That BTW is part of a legacy GPL notice from before 2008. Today I would recommend against Red Hat developers including it. Of course my view is that it has no effect on the substantive GPL license grant.

The second one (https://github.com/nexB/scancode-toolkit/blob/f1f6e2cc29516455ac1732787658ede2b927f8d0/src/licensedcode/data/licenses/red-hat-trademarks.LICENSE) makes sense to me as something to detect because it actually appears as the "license" of a distro package and it is the only set of published terms that covers certain distributed items.

**Comment by pombredanne** [comment]
@richardfontana Thanks for the input! I might still add that old, rarely-but-still-seen pre-2008-ish notice for the sake of being comprehensive.

**Comment by pombredanne** [comment]
A new rule to detect that notice has been added. Closing now.
