### ISSUE TITLE
Install via pip tries to use cache directory in /usr/local/lib

### ISSUE THREAD

**Issue by dengste** [nexB/scancode-toolkit#685]
I installed 'scancode-toolkit' via 'pip' on a Debian 9 box. On startup I get the following backtrace because a normal user obviously does not have permission to create files in /usr/local/lib:

     Traceback (most recent call last):
       File "/usr/local/bin/scancode", line 11, in <module>
	 sys.exit(scancode())
       File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
	 return self.main(*args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/scancode/utils.py", line 76, in main
	 standalone_mode=standalone_mode, **extra)
       File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
	 rv = self.invoke(ctx)
       File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
	 return ctx.invoke(self.callback, **ctx.params)
       File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
	 return callback(*args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
	 return f(get_current_context(), *args, **kwargs)
       File "/usr/local/lib/python2.7/dist-packages/scancode/cli.py", line 386, in scancode
	 scans_cache_class = get_scans_cache_class()
       File "/usr/local/lib/python2.7/dist-packages/scancode/cache.py", line 93, in get_scans_cache_class
	 cache_dir = fileutils.get_temp_dir(unicode(cache_dir), prefix=unicode(timeutils.time2tstamp()) + u'-')
       File "/usr/local/lib/python2.7/dist-packages/commoncode/fileutils.py", line 128, in get_temp_dir
	 return tempfile.mkdtemp(prefix=prefix, dir=base)
       File "/usr/lib/python2.7/tempfile.py", line 339, in mkdtemp
	 _os.mkdir(file, 0700)
     OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/.cache/scan_results_caches/2017-07-13T121227

**Comment by JonoYang** [comment]
Your can opt to install pip packages to your home directory using the `--user` option. If you wanted to install it systemwide, you'd need to run pip with root access.

**Comment by pombredanne** [comment]
@JonoYang I think this has been installed system wide with sudo, right @dengste ?
I reckon this is a somewhat uncommon installation pattern that was never tried before!
What I think happens here is that ScanCode creates a cache for scan results and the license index. This cache is by default always created in the root directory which might end up being (incorrectly I reckon)  `/usr/local/lib/python2.7/.cache` in the case of a global, system-wide installation... hence the permission denied error that you see.

A short term work around might be to do what @JonoYang suggests, e.g. a local user install. Not sure we have tested this either.

Another way is to install with pip in a local virtualenv: this is tested alright

Yet another way is fetch a release from https://github.com/nexB/scancode-toolkit/releases

**Comment by pombredanne** [comment]
Now this is a great bug ... especially since #487 absolutely needs this fixed.

The cache consists of two elements for now: a license index cache that could be global to a given installation and a transient per scan cache that would be best as local to a user.

For the sake of simplification, this might be best written to `~/.cache` when the root directory of the scancode installation is not writeable (which is the case for a system install)....

There is another twist which is the license cache cannot be shared between multiple installations of ScanCode unless they have the exact same code and data.  The license cache invalidation is done by taking a checksums of the installation directory tree per https://github.com/nexB/scancode-toolkit/blob/23d835ff2ad0587eedef4f9eebef87ee1ff0fe48/src/licensedcode/cache.py#L63 ... which breaks entirely when we have a pip installation, either local or global.

So it needs some thoughts.... one possibility could be to get the version of scancode (which is unique even when building/running from a checkout) and get or create a cache directory in `~/.cache/scancode/<version>/` at startup.... this would end in each user directory. 
This cache would then be used for this user's runs both for the scan-level and and the license-level caches.

The whole license cache invalidation and check needs to be reworked too as in a pip install there is no root directory any more: the root ends up being two levels above a module directory hence it lands in the very ugly   `/usr/local/lib/python2.7/` directory. 

@dengste Thanks ++ for this great find!

**Comment by pombredanne** [comment]
This is also related to #357

**Comment by pombredanne** [comment]
> So it needs some thoughts.... one possibility could be to get the version of scancode (which is unique even when building/running from a checkout) and get or create a cache directory in ~/.cache/scancode/<version>/ at startup.... this would end in each user directory.
This cache would then be used for this user's runs both for the scan-level and and the license-level caches.

Another thing which is about  convenience for development or for a tarball/zip release installation: ideally in this case the .cache would be best local to the installation or checkout directory

**Comment by dengste** [comment]
Quick followup: Yes, I ran pip as root and did a systemwide install so that all users on the system can use it. When running as normal user, I would indeed expect scancode to use a directory in the user's home, either ~/.cache, or following the xdg specification (.local/share/scancode or similar).

**Comment by pombredanne** [comment]
@dengste Thanks. I guess ScanCode can run on a non-desktop so may be using a `~/.cache` might be cleaner than relying on the slightly more complex XDG spec and environment (especially since its environment variables may not be present if nothing of X/Freedesktop is installed) ... It also allows to have consistent approach across OSes and seems common enough and clear.

**Comment by pombredanne** [comment]
this is eventually a problem with Docker images too, such as this: https://github.com/heremaps/oss-review-toolkit/blob/docker-improvements-2/Dockerfile

**Comment by pombredanne** [comment]
@sschuberth ping, for reference. This may impact your code .

**Comment by pombredanne** [comment]
@haikoschol 

> Thanks for the detailed writeup! I've made a few attempts at digesting it, but I'm still not sure how exactly this affect #878. Overall it seems very complex to me and I believe a few permutations of use cases and installation methods could be dropped. 

Actually the writeup is complex, but the code ends up being rather simple after all.

> But that goes down a deep rabbit hole where I'm wondering why the configure script and all the custom setup logic exists.

That's a fair question. Very simply, configure + thirdparty exist such that when scancode is used as an app, it is fully self-contained and working out of the box for anyone with only Python.
The alternative could be to use a script which uses requirement files .... but that's exactly what configure is: a script that call pip and requirement files :P
Of course none of this is strictly needed in development and not needed when used as  library.
But at least for dev+tests, it also ensure that there is a strict control of the deps installed and used: here everyone uses strictly the same ones (one or more pinned pip requirements file would achieve the same though it would not help with installing as a self-contained application)

> I fully agree with your suggestions to minimize globals and have "dev mode" not be the default. Adding command line options to set paths for temp and cache files also makes sense.

These are not in the #885 branch.

**Comment by pombredanne** [comment]
@dengste Thank you for your patience!
The code from #885 has been merged in develop and you should no longer have these issues.
The default temp is /tmp and the default cache goes to ~/.cache/scancode-tk
Closing!

**Comment by sschuberth** [comment]
@pombredanne, strictly speaking this should only be closed once there's a new release on PyPI, IMO.

**Comment by pombredanne** [comment]
@sschuberth good point, but I am generally trying to avoid keeping open yet fixed ticket :P I will make an exception!

**Comment by sschuberth** [comment]
IMO part of the "definition of done" should be: The original reporter is in a position to (easily) verify the fix. And here he / she cannot unless you publish a new package 😁

**Comment by pombredanne** [comment]
I sometimes wonder what I would do without you keeping me honest and in check! 👍

**Comment by pombredanne** [comment]
@dengste feedback welcomed. I would like to close this since this has been fixed in develop

**Comment by pombredanne** [comment]
This is merged in develop and all tags since 2.9.7 at least
