### ISSUE TITLE
LGPL and BSD Detection Problem - license mentions with no version

### ISSUE THREAD

**Issue by mjherzog** [nexB/scancode-toolkit#774]
I ran a scan of ntp-4.2.6p5 with ScanCode v2.0.1 and found some anomalies in the reporting of an LGPL (no version) license.  The primary example is in the file ./ntpd/ntpd-opts.c which has the following notice:

 *
 * Generated from AutoOpts 35:0:10 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the ntpd author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * This source file is copyrighted and licensed under the following terms:
 *
 *  see html/copyright.html
*

ScanCode reports the license keys as lgpl and apache-2.0 which presents two problems:
1. The apache-2.0 detection is an error, and BSD was not detected.

 2. The lgpl detection maps to:
- DejaCode License URL of https://enterprise.dejacode.com/urn/urn:dje:license:lgpl which does not exist
- SPDX License Key of "LGPL-2.0+" (which seems reasonable in this context)
ScanCode should probably report the license key as lgpl-2.0 in this context since there is no lgpl key.

I have attached an archive of the JSON scan.
[ntp-scan.zip](https://github.com/nexB/scancode-toolkit/files/1338332/ntp-scan.zip)

**Comment by pombredanne** [comment]
@mjherzog Thanks. 

- About the lgpl report: Since 5f4920f4db32ddb513fe7255e8f75fe1ec764c0d the bare LGPL keys are no longer reported, but instead an LGPL-2.0+ or LGPL-2.1+ if no version is specified (and the same applies to GPL licenses, etc).... So this is fixed in 2.1.... BUT there are also several small issues with the accuracy of the detected licenses in ntp.... So we need to review this in details and add some new rules to improve this.

- ... and the autoopts licensing needs to be reported as a proper license choice.

**Comment by pombredanne** [comment]
See the latest commit and this CSV https://github.com/nexB/scancode-toolkit/blob/d73f5302101648c86132385ef8d189078aca2ab9/ntp-v4.csv for a list of things to review. The notes column tells which row/file new some review of the license detection

**Comment by pombredanne** [comment]
All this has long been fixed and merged... we have now proper L/GPL detection without a version.
