### ISSUE TITLE
[query] Is LibreJS report parity in scope?

### ISSUE THREAD

**Issue by kwill** [nexB/scancode-toolkit#835]
Assume a workflow as follows:
1. With an appropriate tool, download a "complete" web page from a URL into a folder
    * Includes HTML file at given URL + all linked files used to render that page (JavaScript, images...)
2. Scan the folder with scancode-toolkit
3. Generate a report including all licensed and unlicensed resources
4. Visit the same URL with a browser + LibreJS plugin
5. Scan the page with LibreJS
6. Generate a report including all licensed and unlicensed resources

Would LibreJS report parity be in scope for this project? In other words:

1. If LibreJS reports a licensed resource, so does scancode-toolkit
2. If LibreJS reports a resource as unlicensed or non-libre, so does scancode-toolkit
3. If either 1/2 fails, and LibreJS is correct, logging a bug against scancode-toolkit is valid

**Comment by pombredanne** [comment]
@kwill Thanks for the report!
You wrote:

> Would LibreJS report parity be in scope for this project? In other words:
>  1. If LibreJS reports a licensed resource, so does scancode-toolkit
>  2. If LibreJS reports a resource as unlicensed or non-libre, so does scancode-toolkit
>  3. If either 1/2 fails, and LibreJS is correct, logging a bug against scancode-toolkit is valid

yes, yes and yes! With the caveat that LibreJS may do things such as fetching more files which is something that scancode-toolkit would never do: it is strictly offline by design.
 
**Any license detection (either missed, inaccurate, unconclusive)  is a bug here....** and these get fixed swiftly! (and are easy to fix by adding new license detection "rules" as explained here: https://github.com/nexB/scancode-toolkit/wiki/How-to:-Add-new-license-rules-for-enhanced-detection

Note that scancode-toolkit toolkit does not have a notion of libre or non-libre, but only a crude license category, like for this license: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/afl-2.1.yml#L4 and all the licenses: https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data

We could very much add a `libre:` flag to all the licenses YAML files .... of course someone has to do the work ;)

**Comment by kwill** [comment]
> With the caveat that LibreJS may do things such as fetching more files which is something that scancode-toolkit would never do: it is strictly offline by design.

Fair enough. I guess this would be the responsibility of the download tool.

I'm aware of SPDX being interested in license flagging (FSF-libre, OSI-approved, DFSG-compatible...) but this is still in development. If I have time I'll find a reference and open a new ticket to discuss implementation.
