### ISSUE TITLE
Add ScanCode plugin for LKM clues

### ISSUE THREAD

**Issue by chinyeungli** [nexB/scancode-toolkit#850]
PO: should be exposed as a ScanCode plugin

**Comment by mjherzog** [comment]
@pombredanne If we add lkm_clue data from a ScanCode plugin (or other data from another plugin), how will ABC Manager know how to show it?

**Comment by pombredanne** [comment]
@mjherzog it would likely not I guess 
@jdaguil do you have provisions to
1. ignore attributes you do not know about
2. OR support unknown attributes?

**Comment by jdaguil** [comment]
Currently, we ignore unknown attributes. If you were to export, the exported JSON would not contain those unknown attributes because we only store known attributes in the database. It would be difficult to support unknown attributes in an efficient way because columns have to be known beforehand to store them in the database.

**Comment by mjherzog** [comment]
The LKM clues should be implemented as additional optional data element in ScanCode because the clues are file-level data. 
We can create the corresponding issue to display in AbC Manager after we start work on the ScanCode plugin.

**Comment by chinyeungli** [comment]
This has already been implemented in the plugins
