### ISSUE TITLE
Add new BSD variant

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-toolkit#870]
See https://lists.spdx.org/pipermail/spdx-legal/2017-December/002404.html
We may have it already though.

**Comment by yash-nisar** [comment]
@pombredanne Since no one is working on this, I'm taking this one. 😄

**Comment by yash-nisar** [comment]
@pombredanne We already have this one as the `bsdi-license` [here](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsdi-license.LICENSE). Should we consider renaming it to `bsd-1-clause` since [this commit](https://github.com/spdx/license-list-XML/pull/522/commits/fec60d6ff390cd5b1872b646e7f60fcd6017c70e) was recently merged ?

**Comment by pombredanne** [comment]
@yash-nisar we do not rename our license keys... instead if there is one in SPDX that we had, we add the SPDX id to its data (e.g. it YAML file)

**Comment by starlord1311** [comment]
@pombredanne  can i take up this issue?

**Comment by pombredanne** [comment]
@starlord1311 Thanks, but I think based on the comments above this is already worked on. @yash-nisar ping?

**Comment by yash-nisar** [comment]
Yes, I'll open a PR by today.
