### ISSUE TITLE
please use semver for your version numbers

### ISSUE THREAD

**Issue by jeffmcaffer** [nexB/scancode-toolkit#972]
The current version 2.9.0b1 is not a semver. That breaks code that compares one versions output to another.

@pombredanne FYI

**Comment by pombredanne** [comment]
@jeffmcaffer Thanks! I guess I have to figure how the Python https://www.python.org/dev/peps/pep-0440/ meshes exactly with semver for beta ass there are some stuffs which are kinda weird.... I will push a new proper semver'ed one next week

**Comment by pombredanne** [comment]
So I pushed a v2.9.1 after all. Because of a pending ticket in the Python packaging tool, it is not currently possible to produce automatically a semver-compliant pre-release version see https://github.com/pypa/setuptools/issues/308
And for reference the issue comes from https://www.python.org/dev/peps/pep-0440/#pre-release-spelling  e.g. `-` and `_` in beta/prerelease qualifiers are either removed or replaced by a period

**Comment by jeffmcaffer** [comment]
Thanks @pombredanne. It's very interesting that an entire community is unable to use SemVer. Hopefully they'll address the issue. We'll take a look at the new version. This issue can be closed if you like.

**Comment by pombredanne** [comment]
@jeffmcaffer I am keeping this open until is fixed upstream alright

**Comment by sschuberth** [comment]
FYI, we ran into the same issue with [release v3.2.1rc2](https://github.com/nexB/scancode-toolkit/releases/tag/v3.2.1rc2) again: [Semver](https://semver.org/) requires pre-release identifiers to be separated with a dash, i.e. `3.2.1-rc2`. And [ORT](https://github.com/oss-review-toolkit/ort) requires ScanCode to use Semver in order to properly compare ScanCode versions for compatibility of results, which currently requires some ugly work-around on our side.

**Comment by pombredanne** [comment]
@sschuberth oh well :grin: sorry for this, but I am still depending on the Python behaviour yet there is a new way that was added... https://github.com/pypa/setuptools/pull/2026 so the next RC should be semver-like

**Comment by pombredanne** [comment]
We use semver alright now, after a stint in calver land. Closing this now
